### ISSUE TITLE
Cannot install multiple versions of SOPS simultaneously - Proposal to allow flexibility for SOPS installation

### ISSUE THREAD

**Issue by vishaltak** [jkroepke/helm-secrets#100]
Problem: I am trying to create a wrapper on top of Helm for an internal use-case. For this, I need to install multiple version of Helm and it's plugins on the same system. I have managed to install multiple versions of Helm but am limited by the installation of multiple versions of the plugins. e.g. helm-secrets expects SOPS to be at a hard-coded location.

Proposal:
1. Add/change the installation script to allow users to specify the SOPS installation location. Variable can be `HELM_SECRETS_SOPS_PATH` . The default value will be current hard-coded value `/usr/local/bin/sops` in Linux.
2. Modify the command script to lookup for the variable to find the SOPS location.

Comments:
This should not be a breaking change and would allow flexibility to install helm-secret dependencies. It will not only satisfy the above use-case but can serve a bigger audience as well who want control over installation of helm-secrets dependencies.

If the owner is fine with the above proposed changes, I would like to take a shot at this.

Thank you.

**Comment by jkroepke** [comment]
Hi,

which version of helm-secrets you are running?

There is an environment variable called `HELM_SECRETS_SOPS_BIN`. It should accept a full unix path, too.

https://github.com/jkroepke/helm-secrets/blob/fa0c0697ac07d773c0335e5714ddd00173b0766d/scripts/drivers/sops.sh#L3-L9


Understandable, if you did get this info, since its not documented.

**Comment by vishaltak** [comment]
This clearly is a mistake on my part. I was referring to the [v2.0.2](https://github.com/jkroepke/helm-secrets/blob/v2.0.2/install-binary.sh) . It completely missed my mind.

Your suggestion about path manipulations are also great.

Before we close this, is there any variable which can specify with SOPS version to install while installing the helm-secrets plugin? I tried to browse through the shell files but couldn't figure out.

**Comment by jkroepke** [comment]
> Is there any variable which can specify with SOPS version to install while installing the helm-secrets plugin?

In the latest release of helm-secrets, the automatic installation of sops was removed. 

Checkout the [README.md](https://github.com/jkroepke/helm-secrets/blob/v3.5.0/README.md#override-version-of-sops) about how to override the sops version on installation on old helm-secret versions.

**Comment by vishaltak** [comment]
I've upgraded to the last version (v3.6.1) and used `HELM_SECRETS_SOPS_BIN` for specifying sops binary path and things are working great. Thank you for your time and inputs.

I have created a PR to add the documentation for the above env variable, if you are interested in adding the details. - https://github.com/jkroepke/helm-secrets/pull/101
