### ISSUE TITLE
support json sops container (currently only yaml is supported)

### ISSUE THREAD

**Issue by chillum** [jkroepke/helm-secrets#118]
hi,

I'm using `helm-secrets` with [helmfile](https://github.com/roboll/helmfile). and some of my secrets have the `yaml.gotmpl` extension. sops is able to encrypt and decrypt them, but `helm-secrets` doesn't like them and exits with the following error:

```
Error: plugin "secrets" exited with error
COMBINED OUTPUT:
[helm-secrets] Decrypting /tmp/git@github.com_myorg_helm/env/stage-001.yaml.gotmpl
[helm-secrets] File is not encrypted: /tmp/git@github.com_myorg_helm/env/stage-001.yaml.gotmpl 
```

it seems like there's a whitelist for allowed extensions or something like that.

it's also vitally important to helmfile that the unencrypted secret will retain the `yaml.gotmpl` extension, not just `yaml`. (this basically tells it to run this file through the template engine.)

**Comment by jkroepke** [comment]
Hi,

there is no decision based on the file extension.

The logic is here

https://github.com/jkroepke/helm-secrets/blob/8113f88adc223e9c43c0034e598959c1f9fa7eb4/scripts/drivers/sops.sh#L11-L15

Maybe this logic isn't compatible with the newest version of sops?

**Comment by chillum** [comment]
ah, now I get it. the `yaml.gotmpl` encoded by sops not as yaml, but as json. sops encrypts and decrypts it fine, but the encrypted container is json. so this grep fails.

JSON-encoded sops file doesn't contain `(sops|version):`, it contains `"(sops|version)":` instead.

**Comment by chillum** [comment]
maybe it's better just to launch sops without grepping all this as it will fail if the file is not encrypted?
it will report in such cases errors like: `sops metadata not found` or `Error unmarshalling input json`.

**Comment by chillum** [comment]
aha, just removing this logic from `dec.sh` removes this particular error. I'll submit a PR when finished.

now the trick to get it all working is to make decrypted file having the `yaml.gotmpl` extension, now it's just `/tmp/helmfile613722983/default-mychart-mongo-values-86f6f57749`. I've tried setting `HELM_SECRETS_DEC_SUFFIX=.dec.yaml.gotmpl`, but it doesn't seem to do the trick. any clues how do I customize the `/tmp/...` decrypted file extension?

**Comment by jkroepke** [comment]
In general, `HELM_SECRETS_DEC_SUFFIX` is working, since I have unit tests to test this.

I guess helmfile wont pass environment variables to helm.

Looking here
https://github.com/roboll/helmfile/blob/ae942c5288895c84c79171e5446773e4cb41c4ce/pkg/helmexec/exec.go#L268-L269

only environment variables from tillerless `HELM_TILLER_SILENT` and `KUBECONFIG` (if defined) will pass to the helm secrets command.

Maybe it's an issue in helmfile here.

**Comment by jkroepke** [comment]
Aside from that, I could there is still an open issue, since I'm expecting a file named .yaml here.

https://github.com/jkroepke/helm-secrets/blob/d0c53c2e51e7c94fc7d9c35d8e9a1b81894d7db4/scripts/lib/file.sh#L46-L52

Maybe instead remove .yaml and append .yaml.dec here, just append `.dec` would be a general approach here.

**Comment by chillum** [comment]
hm, to me it appears like .dec is not applied at all in this use case:
```
Decrypting secret /tmp/git@github.com_myorg_helm/env/stage-001.yaml.gotmpl
[helm-secrets] Decrypting /tmp/git@github.com_myorg_helm/env/stage-001.yaml.gotmpl
Templating release=myapp-mongo, chart=mongo in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:
PATH: /usr/local/bin/helm ARGS: 0: /usr/local/bin/helm (19 bytes) 1: template (8 bytes) 2: myapp-mongo (12 bytes) 3: mongo (5 bytes) 4: --namespace (11 bytes) 5: default (7 bytes) 6: --values (8 bytes) 7: /tmp/helmfile613722983/default-myapp-mongo-values-86f6f57749 (61 bytes) 8: --api-versions=v1 (17 bytes) ERROR: exit status 1 EXIT STATUS 1 STDERR: Error: template: mongo/templates/service.yaml:1:16: executing "mongo/templates/service.yaml" at <.Values.global.provider>: nil pointer evaluating interface {}.provider 
```

i.e. helmfile successfully decrypts `stage-001.yaml.gotmpl` to `/tmp/helmfile613722983/default-myapp-mongo-values-86f6f57749`, but then fails to process is as a template (as it doesn't have the `.gotmpl` extension).

**Comment by jkroepke** [comment]
Which version of helm secrets are you running?

```
jkr@joe-nb a % helm secrets dec $PWD/stage-001.yaml.gotmpl
[helm-secrets] Decrypting /Users/jkr/IdeaProjects/helm-secrets/a/stage-001.yaml.gotmpl
jkr@joe-nb a % ls
stage-001.yaml.gotmpl           stage-001.yaml.gotmpl.yaml.dec
```

**Comment by chillum** [comment]
[this one](https://github.com/Alliera/helm-secrets), it's your master + a patch to make JSON sops containers work.

yeah, it works for me as well. and I've verified the `HELM_SECRETS_DEC_SUFFIX` works with `helm secrets dec`.
so probably the error is in helmfile, either not passing the env or in some custom logic to name the output file (I believe, actually helmfile passes an output file name, so this is the culprit).

**Comment by chillum** [comment]
I've created [an issue for helmfile](https://github.com/roboll/helmfile/issues/1878), it seems like the secrets parsing is broken on their side (and it's probably not the extension).

the most I can do within current issue is to patch helm-secrets to support SOPS JSON containers, so changing the title.
