### ISSUE TITLE
[question] how to integrate with vault approle?

### ISSUE THREAD

**Issue by tuananh** [jkroepke/helm-secrets#139]
i cant seem to find an example of using helm-secrets with vault via approle. can anyone point me to the location of the docs?

**Comment by jkroepke** [comment]
Hi,

helm-secrets doesn't handle the auth to vault. helm-secrets is using the vault cli to fetch credentials.
Any authentication supported by the vault cli is supported.

By reading the [docs](https://learn.hashicorp.com/tutorials/vault/approle#step-5-read-secrets-using-the-approle-token) of vault, you can define a environment variable called VAULT_TOKEN that contains the app role token.

**Comment by tuananh** [comment]
Thanks @jkroepke. i need to do an [additional step](https://learn.hashicorp.com/tutorials/vault/approle#step-4-login-with-roleid-secretid) before i can grab the token. how can i do that with helm-secrets?

**Comment by jkroepke** [comment]
You can run the additional step before call helm secrets.

Maybe I dont get the point.

**Comment by tuananh** [comment]
What i mean was, do I define those additional step somewhere in helm-secrets or it's outside of this project's scope?

**Comment by jkroepke** [comment]
helm-secrets currently requires a authenticated context/environment.

There are tons of ways to authentificate the context (keep in mind, additionally sops supports multiple clouds) that the authentification of the secret source is out of scope of helm secrets. Except there is an valid use case to do it inside helm secrets.

**Comment by tuananh** [comment]
Thank you. Got it
