### ISSUE TITLE
Wrong HELM_SECRETS_SOPS_PATH variable name in readme

### ISSUE THREAD

**Issue by gvorobyo** [jkroepke/helm-secrets#140]
### Current Behavior

HELM_SECRETS_SOPS_BIN

See https://github.com/jkroepke/helm-secrets/blob/v3.8.3/scripts/drivers/sops.sh

```
#!/usr/bin/env sh

_SOPS="${HELM_SECRETS_SOPS_BIN:-sops}"

```

### Expected Behavior

HELM_SECRETS_SOPS_PATH per Readme:

![image](https://user-images.githubusercontent.com/78349264/134530148-9ce9931e-75b3-4529-8dbf-da72fed646bc.png)

**Comment by jkroepke** [comment]
Good catch!

I added HELM_SECRETS_SOPS_PATH at the code which is preferred over HELM_SECRETS_SOPS_BIN for now, since HELM_SECRETS_SOPS_PATH feels more correct than HELM_SECRETS_SOPS_BIN.
