### ISSUE TITLE
[Q] Example of usage with GCP Secret Manager

### ISSUE THREAD

**Issue by raszkiewicz** [jkroepke/helm-secrets#144]
Is there any good example how to use it with GCP Secret Manger and images pulled from the docker hub (like MySQL, MongoDB, Rabbit MQ etc)?

**Comment by jkroepke** [comment]
Currently, not. 

I'm currently working on an integration with [vals](https://github.com/variantdev/vals) and vals is supporting GCP Secrets Manager.

**Comment by raszkiewicz** [comment]
OK, I will follow this project as it looks very promising.
