### ISSUE TITLE
How to diff or install helm chart with encrypted K8s secret manifests?

### ISSUE THREAD

**Issue by jaythamke** [jkroepke/helm-secrets#156]
Hi Jan,

I know that helm-secrets plugin uses sops encrypted secrets as values file to override the secret value in K8s secrets template manifest. 
I have a [generic helm chart](https://github.com/jaythamke/generic-helm-chart) and I wanted to use helm-secrets plugin to diff, template etc. the chart by using sops-encrypted K8s secret manifest. Do you know how can I achieve it?

thanks,
Jayesh

**Comment by jkroepke** [comment]
Hey,

sorry. No idea. helm-secrets only supports encrypted values, not encrypted manifests.

Maybe, the post renderer functionality can you help here https://helm.sh/docs/topics/advanced/#post-rendering
