### ISSUE TITLE
Improve the Argo CD Integration Documentation

### ISSUE THREAD

**Issue by peyerroger** [jkroepke/helm-secrets#159]
### Problem Statement

It is not very straight forward to use Helm Secrets with Argo CD.

### Proposed Solution

Improve the documentation.

### Acceptance Criteria

As a user it should be simple to get Helm Secrets to work with Argo CD

**Comment by jkroepke** [comment]
> As a user it should be simple ...

I will take a look at the age encryption since, it's a way more simpler solution to gpg. 

https://github.com/mozilla/sops#encrypting-using-age
