### ISSUE TITLE
Helm template temporary file too long

### ISSUE THREAD

**Issue by luisfmcalado** [jkroepke/helm-secrets#167]
### Current Behavior

I was setting up Helm secrets for ArgoCD deployment and got the following error when importing the key.

```
 mktemp: failed to create directory via template '/tmp/tmp.fjNVPdZAIK/tmp.AxRzHACJg6/tmp.Gpd5hRlXku/tmp.Tns7tIZyVU/tmp.FSZWjiQlhs/tmp.eTSrztcsXq/tmp.7Y6aJ64Ktz/tmp.Dq0mN1jgek/tmp.ZlrVzUvqhX/tmp.j6ayPfkfbm/tmp.ioMcELVCDD/tmp.FCwDyjFbz9/tmp.8UkhYeTWkF/tmp.v7H7fsYJg5/tmp.bJ3MA6R5Vk/tmp.d8g6JlQzw3/tmp.tGB2ZAIyLe/tmp.PDddJi6hpH/tmp.ucj3OLCfSq/tmp.znW6ah1DgA/tmp.S8rBfXw8z9/tmp.7nRTV52PNA/tmp.Onsr1wGJN3/tmp.uqKcxuQJPS/tmp.H1Xozx2tAj/tmp.OMBbWfoKRg/tmp.b8Ty8xBKlv/tmp.JoMzqqu78m/tmp.z36vvr5l0r/tmp.0dYuVFGji1/tmp.OSGTA9Vxob/tmp.Ps0Vl6MAzu/tmp.jU3enKmAy1/tmp.hbW7g8TSz4/tmp.nSKkpwbwyK/tmp.qXVy4S7g8p/tmp.DpnssbtwUx/tmp.GC4oNQNBYB/tmp.GTAZPkNOdw/tmp.RMw4OGBOGJ/tmp.pLu8lgbCfE/tmp.Vix5Bf1my1/tmp.3oZqS1mmBp/tmp.hQctaqZQAn/tmp.sdbWj1abBK/tmp.CdJgZfzzRO/tmp.B0soHsK0hf/tmp.XC0mSc21HV/tmp.3nr6Pxzkq9/tmp.wtBh7xY01O/tmp.CIpLUfq2FR/tmp.hw9okChPjb/tmp.rx448WHjUj/tmp.BZg9JSemHG/tmp.d8N7IgWsyW/tmp.ekgOkfbdAk/tmp.UmJVGWeUtL/tmp.Q2vKFrsiqV/tmp.jbldGh6mzp/tmp.NeLMGgUkcj/tmp.dj9cSpRaJS/tmp.LWbxoQIB6v/tmp.8fjATmGDgH/tmp.58qUJmbrkX/tmp.SE4Kq4KQXY/tmp.0LCuNTILXC/tmp.N5pf6rbpn9/tmp.vt00dgD5rW/tmp.4PXgRbDfgg/tmp.08UKqDB5Bn/tmp.o37UErfCK0/tmp.UMaGhYrF39/tmp.Jp8c3rV8V4/tmp.zQxLvATwwP/tmp.LB7UmiLlRY/tmp.Xw4HbTv9BV/tmp.BZd2QBeSBp/tmp.eGWt0i2j5n/tmp.DDiWLAahte/tmp.aYM7caQ03V/tmp.ZooZkUuu2K/tmp.HjvQSKwvoq/tmp.dlMLRPqPKU/tmp.3WzZOVIRmX/tmp.eyLwYIl50a/tmp.l1nwfhpuQz/tmp.9JjFSV51dD/tmp.U9Rzta51hu/tmp.4n40WQzAhK/tmp.mC7h47JfDm/tmp.S13kBUVzZP/tmp.iJOkJUr7G0/tmp.894rHfRzRw/tmp.dCSnreK8Vy/tmp.vKmNKA3vCZ/tmp.doUyOAQ3Ul/tmp.dXQndnpEbg/tmp.wX0rhiNXsO/tmp.ZfsEs5EtfB/tmp.ycZvAxPTN2/tmp.7HyAuNM0fz/tmp.yf4YQJeb28/tmp.ZoxGVQ5L53/tmp.DQjmLj5jOU/tmp.95rI8ctAVF/tmp.8eGYo439g0/tmp.rQeFt8Utmy/tmp.9Q31L68swZ/tmp.qlj3SlgRYk/tmp.g4kDn61Mi2/tmp.MuLeIVA4AE/tmp.OxiTHkqS6I/tmp.Yq5Fn2708X/tmp.SVcYZOni0r/tmp.onYMI9mcdK/tmp.WhQdCTGV6V/tmp.W8xvYB0GJQ/tmp.3PHBqwoRDU/tmp.RbKHM7Zm3O/tmp.qqhkeqSnNH/tmp.1FExThqGk8/tmp.dMU3fMXJe9/tmp.ModWXXd00f/tmp.vIYq1eYQnB/tmp.J7f1q08oHy/tmp.riI4V6m4WQ/tmp.EMfnCjR2Vv/tmp.VY69dTFRwZ/tmp.zyHq8ivaa4/tmp.7R6oM1A9CV/tmp.HZDPN6sMpd/tmp.rgRN6DbfzP/tmp.D0aCw2Uw3A/tmp.56he5bTfl5/tmp.1Ro1xI01rT/tmp.VAeY1ezQny/tmp.hyMDiEmtnr/tmp.ZZpZ7PePFE/tmp.iMInAaEpbN/tmp.CDPv6kNOQj/tmp.NlHiGAVnby/tmp.qm64yv8All/tmp.loDrY3AlZh/tmp.GcnQINFy3J/tmp.KcV1Li9an9/tmp.9VjVxzax3d/tmp.mKcKxDpAh1/tmp.GFovGdyTTN/tmp.cjE1615y5Q/tmp.Bdb1mYxLJ7/tmp.n4hCJyDCsL/tmp.5qxS86QnOw/tmp.O0hWHrCI4v/tmp.DQfprGGg6I/tmp.KLEwXXmaEY/tmp.xZkH39KbvU/tmp.vnOfc4htOj/tmp.Qetiws33gS/tmp.bs68h8hatH/tmp.C2LcpIHPav/tmp.qQ7sXC5djn/tmp.lgYXMez9t1/tmp.bKvxLBTNkW/tmp.VcyPicWFjg/tmp.jcL4gDWe1M/tmp.8N3DWCLsGE/tmp.kktpUAuw2k/tmp.1CXXKdojIH/tmp.PFbjRtdFgT/tmp.Ssjp6jKOLK/tmp.fcWZZugsPG/tmp.dVvZbuzn8R/tmp.lYxbSxdzXV/tmp.09K1VExc0L/tmp.W5V58UAgQh/tmp.ufIdQC3yIY/tmp.rBWOYKoU8U/tmp.7450DAjoVD/tmp.6UNTt3TRF7/tmp.VQl6E43WpH/tmp.06xDWsD5PU/tmp.rzUBZ39FSg/tmp.GDlF5yCQmR/tmp.3S0GUy3Nif/tmp.IU8Y2JP7Vd/tmp.r2rCfBU5sA/tmp.lnzDHOn7bI/tmp.bqM3lyyPHv/tmp.5ffCN8gWQZ/tmp.MQIxEu9nY5/tmp.M0TIXSXjF7/tmp.ptPE5Iilb6/tmp.ZC3EHwkvkU/tmp.a8s7e5zFn1/tmp.hbyAkZHERY/tmp.CouJhkYVOc/tmp.WwCVynMFWA/tmp.5tjg37N4K3/tmp.1bqcJbMrtZ/tmp.QDwaUdZQxK/tmp.ckM79hdKDO/tmp.O6W7tAIkbf/tmp.Hq4rAis770/tmp.0cvEySyhiH/tmp.6cUOCresRh/tmp.9zebDbra5X/tmp.jtvIua5AbM/tmp.tSeXLYYWlz/tmp.kJvPS1iWdZ/tmp.l6CuHA7CrM/tmp.J3UERKtVvy/tmp.avCoxo9GJr/tmp.0mpodArGns/tmp.7BL4jYXtyq/tmp.rNfQHTyAvV/tmp.c4rI48HE4Z/tmp.qUT8xuFJ6w/tmp.vUl9LYG7J5/tmp.b90ne2w5UK/tmp.ifAXpwSpXT/tmp.aL3HoAUxL3/tmp.8vIcdEg1Ni/tmp.kjah5Kn4as/tmp.cKRbCJh6MP/tmp.mU7H3SGxKG/tmp.DZOgBoMeMe/tmp.viAe0oDBmm/tmp.QoAn6UOyEf/tmp.ADL7DFa1R2/tmp.sekWhqNqLH/tmp.mhTaRJUCzG/tmp.eIPRkhLG88/tmp.rPZV2oO6H6/tmp.jySDCEZZAi/tmp.N9oU7ci3H1/tmp.4TvJY6s6VP/tmp.YyyjT0k6Ec/tmp.suu00Io3ZF/tmp.VErMYXmyjI/tmp.f6vGCss94h/tmp.jeQqzmrjT6/tmp.0qLPzEM8FE/tmp.nq9K4UOBMg/tmp.xLxO1DDkNa/tmp.m3AfgzTbzS/tmp.imWpyOSzdo/tmp.nNRSBgqc1C/tmp.oH89d8fNKo/tmp.mkoEfeuwpn/tmp.jys4Bt1VCR/tmp.YaZxrO3Hbc/tmp.xoNkVwQOmZ/tmp.Cc65rQtMmL/tmp.1W61eMvE5W/tmp.nLXbUCilCA/tmp.i8BdCWq94Z/tmp.D8rJ1m8MZu/tmp.hmUO0aOQEM/tmp.QL2BQfxGvn/tmp.98mno6Ngq4/tmp.InpFKrooON/tmp.MjXyW5wwgC/tmp.Q0nmAgZIGV/tmp.DO3QIuxvMl/tmp.j50MVFo3fa/tmp.UturnsCPKG/tmp.WbJrd3r389/tmp.Kvy0RnuEkw/tmp.lqRdkM47M0/tmp.cxu1yAV6so/tmp.UgsFw78Jsq/tmp.pNoDhI1l9f/tmp.XXXXXXXXXX': File name too long\nError: plugin \"secrets\" exited with error\n[helm-secrets] File does not exist: secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml\
```

The valuefile is configured with `secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml`.

### Expected Behavior

I was expecting that the secrets was decrypted and helm use the `secrets.yaml.dec`.

### Environment

- Helm Version: 3.6.0
- OS: ubuntu 21.04

### Anything else?

As a workaround I baked the age key into the ArgoCD custom image. And helm secrets is able to decrypt the secret if the valuefile is `secrets.yaml`.

**Comment by jkroepke** [comment]
Mount the key to `/helm-secrets-private-keys/key.txt` wont work, while add the file via `docker build` works?

**Comment by luisfmcalado** [comment]
> Mount the key to `/helm-secrets-private-keys/key.txt` wont work, while add the file via `docker build` works?
> 
> Can you please verify that you are using helm-secrets 3.10.0?

Isn't working when using the protocol handler. yes, I'm running the helm secrets version 3.10.0.

**Comment by jkroepke** [comment]
I‘m able to reproduce this error. Looks like helm-secrets is wrongly strip the scheme from that url which results in a infinite loop.

is it possible to run the main branch on your side with env var HELM_SECRETS_DEBUG=true ?

if you could share the debug output, i would understand why this error appears.

**Comment by jkroepke** [comment]
Hi @luisfmcalado 

may take a look at https://github.com/jkroepke/helm-secrets/pull/170 This add a more strict behavior. I guess something is wrong around identify the correct scheme. The version on main would always fallback to 'nothing', but now this should be result in an error.

**Comment by luisfmcalado** [comment]
thank you for your time @jkroepke. It check with the new version and enable the HELM_SECRETS_DEBUG=true.

**Comment by luisfmcalado** [comment]
`
VDEtd3p9ba/tmp.QYVNy79oUE/tmp.T27ukyT2ce/tmp.A1PoUHYZTZ/tmp.fcDXi1M9rg/tmp.hJTd6tvDhn/tmp.L5zrJFExkG/tmp.sqmbHATCZJ/tmp.ragiYASWoW/tmp.iJyjyiQceS/tmp.KLnw3AvFPG/tmp.O9eAvk0LwI/tmp.FUsQqGSUsP/tmp.wzVt3H6Cb0/tmp.olQdQGKrJ2/tmp.stq1qT1ELM/tmp.Q1iVwlZmMP/tmp.BKXn7uWJLe/tmp.nd9ByTIzDE/tmp.Bj9AyCoOmB/tmp.wXCNnhUpOm/tmp.r1oa5NxmmZ/tmp.qi0X0g8uGw/tmp.EwWlCRFTWh/tmp.dChu6i6pKr/tmp.DKsc4MFm3K/tmp.xFJBswOnTc/tmp.Mmmnpgm00R/tmp.CyO8elz8yb/tmp.PHozPFkOv0/tmp.hc3oxUpXeH/tmp.pV91G5WQ3m/tmp.4VnX0ZIr7m/tmp.vDW5BlemxN/tmp.eOnONZvYnv/tmp.wvqUocgL6g/tmp.ofLUVse4yn/tmp.wZ4LaSiUSa/tmp.B3loXWNWqp/tmp.InwhX04mlU/tmp.r2Vrymg0e9/tmp.HToiV7OLt3/tmp.In6DqmWroJ/tmp.lCHnzDjwr8/tmp.VoytpezjY5/tmp.6L56ZS6Uih/tmp.qoh7UUs76I/tmp.bk5Wfpc6g1/tmp.D1p8dqsjX6/tmp.E1blCtNyir/tmp.OSV9TNTFPR/tmp.yBv5ekCDUP/tmp.EDCitJYQBn/tmp.7NIB9aGQbs/tmp.OLKp0jZShm/tmp.GOGukj7meL/tmp.ZtWapYTpdr/tmp.JWn610nYry/tmp.PQr5itjey5/tmp.rFgypmRvou/tmp.DXYzEmXCMj/tmp.ZMyB8v2Dfd/tmp.ERk3N6axI1/tmp.5A1J9TXLrQ/tmp.Bw7y68X9SR/tmp.RqvSfyIr9f/tmp.YeCRfwayG9/tmp.F3EKULVSiH/tmp.13ZRmsQwop/tmp.dD1HtgRvO8/tmp.NvxC9R8ioM/tmp.L8VvKt7tM2/tmp.dyxXHOyI6H/tmp.NxzEz6BELF/tmp.itsCem4is7/tmp.oo00BDR6R6/tmp.x5nSnPVRNi/tmp.yGz2VyBcc8/tmp.lV5xAQp6RL/tmp.sTobfEa2kZ/tmp.lWgPvR6SIL/tmp.LetSI3HdMB/tmp.9hiXnMG2NQ/tmp.UHLw1XmVvF/tmp.5gEaWZlFEV/tmp.i317CSPsiJ/tmp.IWHwu9a56R/tmp.btgZ0R1kA1/tmp.QJT3t0u7Gy/tmp.NecJphBpTs/tmp.r7uopjKbSk/tmp.AJinZRssaR/tmp.H0TGD7lHoZ/tmp.qGapWrgedR/tmp.bv3lCZQTbi/tmp.DwYiimTzLN/tmp.SpQREPB9QE/tmp.nwjLuM3yi2/tmp.c1Hfl8V76d/tmp.5FVj6APiIW/tmp.YYrU8YYdFT/tmp.UST941ctnT/tmp.gUXZVQzrAT/tmp.tC2NjjZtkI/tmp.jR5RjqE0do/tmp.2SQkGpx5gd/tmp.7fbWwRmB0O/tmp.1mwaHdk2e8/tmp.aKU0Oc4sql/tmp.J1XELRt0xw/tmp.XbbV1vO4xc/tmp.xtG05DODud/tmp.mV1V4NYhev/tmp.VpjMQO38FY/tmp.bj3HUdKxXl\nError: plugin \"secrets\" exited with error\n+ exit 1\n+ real_file=\n+ error [helm-secrets] File does not exist: %s\\n secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml\n+ [ 2 -le 1 ]\n+ format=[helm-secrets] File does not exist: %s\\n\n+ shift\n+ printf [helm-secrets] File does not exist: %s\\n secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml\n[helm-secrets] File does not exist: secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml\n+ exit 1\n+ _trap\n+ command -v _trap_hook\n+ _trap_hook\n+ [ -s /tmp/tmp.dFLIr5JhJ8/tmp.8EYZROOvUh/tmp.o6qjgydLuc/tmp.D3nCISPV6X/tmp.sgv9tGkCws/tmp.1w401CdJlR/tmp.4XaHmNTJDA/tmp.GdQELzHDJZ/tmp.5rFwI8AWvf/tmp.tm0I92HDW0/tmp.hpUwKWxbnm/tmp.qk8dbDcbrm/tmp.KeKROd2VrH/tmp.q0FhwsfQRn/tmp.nES6PmziD2/tmp.VDEtd3p9ba/tmp.QYVNy79oUE/tmp.T27ukyT2ce/tmp.A1PoUHYZTZ/tmp.fcDXi1M9rg/tmp.hJTd6tvDhn/tmp.L5zrJFExkG/tmp.sqmbHATCZJ/tmp.ragiYASWoW/tmp.iJyjyiQceS/tmp.KLnw3AvFPG/tmp.O9eAvk0LwI/tmp.FUsQqGSUsP/tmp.wzVt3H6Cb0/tmp.olQdQGKrJ2/tmp.stq1qT1ELM/tmp.Q1iVwlZmMP/tmp.BKXn7uWJLe/tmp.nd9ByTIzDE/tmp.Bj9AyCoOmB/tmp.wXCNnhUpOm/tmp.r1oa5NxmmZ/tmp.qi0X0g8uGw/tmp.EwWlCRFTWh/tmp.dChu6i6pKr/tmp.DKsc4MFm3K/tmp.xFJBswOnTc/tmp.Mmmnpgm00R/tmp.CyO8elz8yb/tmp.PHozPFkOv0/tmp.hc3oxUpXeH/tmp.pV91G5WQ3m/tmp.4VnX0ZIr7m/tmp.vDW5BlemxN/tmp.eOnONZvYnv/tmp.wvqUocgL6g/tmp.ofLUVse4yn/tmp.wZ4LaSiUSa/tmp.B3loXWNWqp/tmp.InwhX04mlU/tmp.r2Vrymg0e9/tmp.HToiV7OLt3/tmp.In6DqmWroJ/tmp.lCHnzDjwr8/tmp.VoytpezjY5/tmp.6L56ZS6Uih/tmp.qoh7UUs76I/tmp.bk5Wfpc6g1/tmp.D1p8dqsjX6/tmp.E1blCtNyir/tmp.OSV9TNTFPR/tmp.yBv5ekCDUP/tmp.EDCitJYQBn/tmp.7NIB9aGQbs/tmp.OLKp0jZShm/tmp.GOGukj7meL/tmp.ZtWapYTpdr/tmp.JWn610nYry/tmp.PQr5itjey5/tmp.rFgypmRvou/tmp.DXYzEmXCMj/tmp.ZMyB8v2Dfd/tmp.ERk3N6axI1/tmp.5A1J9TXLrQ/tmp.Bw7y68X9SR/tmp.RqvSfyIr9f/tmp.YeCRfwayG9/tmp.F3EKULVSiH/tmp.13ZRmsQwop/tmp.dD1HtgRvO8/tmp.NvxC9R8ioM/tmp.L8VvKt7tM2/tmp.dyxXHOyI6H/tmp.NxzEz6BELF/tmp.itsCem4is7/tmp.oo00BDR6R6/tmp.x5nSnPVRNi/tmp.yGz2VyBcc8/tmp.lV5xAQp6RL/tmp.sTobfEa2kZ/tmp.lWgPvR6SIL/tmp.LetSI3HdMB/tmp.9hiXnMG2NQ/tmp.UHLw1XmVvF/tmp.5gEaWZlFEV/tmp.i317CSPsiJ/tmp.IWHwu9a56R/tmp.btgZ0R1kA1/tmp.QJT3t0u7Gy/tmp.NecJphBpTs/tmp.r7uopjKbSk/tmp.AJinZRssaR/tmp.H0TGD7lHoZ/tmp.qGapWrgedR/tmp.bv3lCZQTbi/tmp.DwYiimTzLN/tmp.SpQREPB9QE/tmp.nwjLuM3yi2/tmp.c1Hfl8V76d/tmp.5FVj6APiIW/tmp.YYrU8YYdFT/tmp.UST941ctnT/tmp.gUXZVQzrAT/tmp.tC2NjjZtkI/tmp.jR5RjqE0do/tmp.2SQkGpx5gd/tmp.7fbWwRmB0O/tmp.1mwaHdk2e8/tmp.aKU0Oc4sql/tmp.J1XELRt0xw/tmp.XbbV1vO4xc/tmp.xtG05DODud/tmp.mV1V4NYhev/tmp.VpjMQO38FY/7kPCds ]\n+ rm -rf /tmp/tmp.dFLIr5JhJ8/tmp.8EYZROOvUh/tmp.o6qjgydLuc/tmp.D3nCISPV6X/tmp.sgv9tGkCws/tmp.1w401CdJlR/tmp.4XaHmNTJDA/tmp.GdQELzHDJZ/tmp.5rFwI8AWvf/tmp.tm0I92HDW0/tmp.hpUwKWxbnm/tmp.qk8dbDcbrm/tmp.KeKROd2VrH/tmp.q0FhwsfQRn/tmp.nES6PmziD2/tmp.VDEtd3p9ba/tmp.QYVNy79oUE/tmp.T27ukyT2ce/tmp.A1PoUHYZTZ/tmp.fcDXi1M9rg/tmp.hJTd6tvDhn/tmp.L5zrJFExkG/tmp.sqmbHATCZJ/tmp.ragiYASWoW/tmp.iJyjyiQceS/tmp.KLnw3AvFPG/tmp.O9eAvk0LwI/tmp.FUsQqGSUsP/tmp.wzVt3H6Cb0/tmp.olQdQGKrJ2/tmp.stq1qT1ELM/tmp.Q1iVwlZmMP/tmp.BKXn7uWJLe/tmp.nd9ByTIzDE/tmp.Bj9AyCoOmB/tmp.wXCNnhUpOm/tmp.r1oa5NxmmZ/tmp.qi0X0g8uGw/tmp.EwWlCRFTWh/tmp.dChu6i6pKr/tmp.DKsc4MFm3K/tmp.xFJBswOnTc/tmp.Mmmnpgm00R/tmp.CyO8elz8yb/tmp.PHozPFkOv0/tmp.hc3oxUpXeH/tmp.pV91G5WQ3m/tmp.4VnX0ZIr7m/tmp.vDW5BlemxN/tmp.eOnONZvYnv/tmp.wvqUocgL6g/tmp.ofLUVse4yn/tmp.wZ4LaSiUSa/tmp.B3loXWNWqp/tmp.InwhX04mlU/tmp.r2Vrymg0e9/tmp.HToiV7OLt3/tmp.In6DqmWroJ/tmp.lCHnzDjwr8/tmp.VoytpezjY5/tmp.6L56ZS6Uih/tmp.qoh7UUs76I/tmp.bk5Wfpc6g1/tmp.D1p8dqsjX6/tmp.E1blCtNyir/tmp.OSV9TNTFPR/tmp.yBv5ekCDUP/tmp.EDCitJYQBn/tmp.7NIB9aGQbs/tmp.OLKp0jZShm/tmp.GOGukj7meL/tmp.ZtWapYTpdr/tmp.JWn610nYry/tmp.PQr5itjey5/tmp.rFgypmRvou/tmp.DXYzEmXCMj/tmp.ZMyB8v2Dfd/tmp.ERk3N6axI1/tmp.5A1J9TXLrQ/tmp.Bw7y68X9SR/tmp.RqvSfyIr9f/tmp.YeCRfwayG9/tmp.F3EKULVSiH/tmp.13ZRmsQwop/tmp.dD1HtgRvO8/tmp.NvxC9R8ioM/tmp.L8VvKt7tM2/tmp.dyxXHOyI6H/tmp.NxzEz6BELF/tmp.itsCem4is7/tmp.oo00BDR6R6/tmp.x5nSnPVRNi/tmp.yGz2VyBcc8/tmp.lV5xAQp6RL/tmp.sTobfEa2kZ/tmp.lWgPvR6SIL/tmp.LetSI3HdMB/tmp.9
`
Sample from logs. I've checked that the file is properly mounted.

**Comment by jkroepke** [comment]
the logs are stripped. It just contains the last lines. Try to execute the command inside the repo server pod to gain more output. Mainly the head of the logs are more interesting.

**Comment by luisfmcalado** [comment]
[logs.tar.gz](https://github.com/jkroepke/helm-secrets/files/7611881/logs.tar.gz)

**Comment by jkroepke** [comment]
What is the helm binary `_helm` in your setup?

**Comment by luisfmcalado** [comment]
Indeed it was the wrapper I introduced by reading other tutorials. I have remove the wrapper completely and only installed the helm secrets plugin and it worked like a charm. Thank you for the given help! 
We can close the bug.
