### ISSUE TITLE
Error "sops: not found" after installing helm secrets plugin

### ISSUE THREAD

**Issue by MurzNN** [jkroepke/helm-secrets#177]
### Current Behavior

The `helm-secrets` plugin installs successfully without errors:
```
$ helm plugin install https://github.com/jkroepke/helm-secrets
Installed plugin: secrets
```
But if I try to encrypt some file, I got the error:
```
$ helm secrets enc secrets.yaml
Encrypting secrets.yaml
/home/user/.local/share/helm/plugins/helm-secrets/scripts/run.sh: 8: sops: not found
Error: plugin "secrets" exited with error
```
As I understand from docs, the `sops` package must be downloaded automatically when plugin installs, but seems it isn't happen.

### Expected Behavior

Plugin must show some warning, if the system misses the `sops` package, and it fails to install its own.

Or the `helm-secrets` plugin stops installing it's own `sops` package on self-installing action by default, and needs some argument to install it?

### Steps To Reproduce

1. Install plugin on Ubuntu 20.04 without pre-installed `sops` package.

2. Try to encrypt some file via command `helm secrets enc secrets.yaml` and got an error:

```
$ helm secrets enc secrets.yaml
Encrypting secrets.yaml
/home/user/.local/share/helm/plugins/helm-secrets/scripts/run.sh: 8: sops: not found
Error: plugin "secrets" exited with error
```

### Environment

- Helm Version: v3.7.0
- Helm Secrets Version: 3.12.0-dev
- OS: Ubuntu 20.04
- Shell: bash

**Comment by jkroepke** [comment]
> As I understand from docs, the sops package must be downloaded automatically when plugin installs, but seems it isn't happen.

Which document describes an automatic installation?

[Until 3.6.0](https://github.com/jkroepke/helm-secrets/blob/main/CHANGELOG.md#360---2021-03-29), helm-secrets installed sops. But its not the case anymore.

**Comment by MurzNN** [comment]
Thanks for pointing to this! Seems I've seen this in old version of documentation (in some fork of this repo), because can't find anything about auto-installing `sops` in current version of documentation.

So maybe re-implement installing `sops` via some dedicated flag, or document, that now (after version 3.6) we need to install `sops` or other secret driver manually?

**Comment by jkroepke** [comment]
Its documented here: https://github.com/jkroepke/helm-secrets/wiki/Secret-Driver#list-of-implemented-secret-drivers

In https://github.com/jkroepke/helm-secrets/commit/e1f7f30ffaee40437c8526928cdfc336d233b02c I added a note on installation step that additional steps may required.

**Comment by MurzNN** [comment]
Thank you, now all is clear!
