### ISSUE TITLE
Example with sops age encryption configuration

### ISSUE THREAD

**Issue by MurzNN** [jkroepke/helm-secrets#179]
### Problem Statement

I've configured `sops` with modern `age` encryption backend and it works via direct commands like this:
```
sops --encrypt --age age16nq3gv6rjuqkk73wkt5ek0qm9m7gesnj4enhwqm2cqv78p8whsssyed2kw ./secrets.yaml > ./secrets.yaml.enc
```
But I can't understand how to configure helm secrets plugin to work with age mode of `sops`? 

If I simply run the `helm secrets enc file.yaml` command - I've got an error:
```
$ helm secrets enc ./secrets.yaml 
Encrypting ./secrets.yaml
config file not found and no keys provided through command line options
Error: plugin "secrets" exited with error
```

What config file I must create and in what format, to tell that I want to use `sops` with `age` backend in helm secrets plugin?

Can you please add documentation with configuration examples? Thanks!

### Proposed Solution

Seems we need to pass the `--age age16nq3gv6rjuqkk73wkt5ek0qm9m7gesnj4enhwqm2cqv78p8whsssyed2kw` argument using `-a` argument to encode? Something like this:
```
$ helm secrets -a "--age age16nq3gv6rjuqkk73wkt5ek0qm9m7gesnj4enhwqm2cqv78p8whsssyed2kw" enc ./secrets.yaml
```
And for decode - some other argument? The direct argument for `sops` must be like this:
```
$ age --decrypt -i ~/.config/sops/keys.txt ./secrets.yaml.enc
```
and it decrypts well, but when I try to do the same with `helm secrets` - it fails with error:
```
$ helm secrets -a "-i ~/.config/sops/keys.txt" dec ./secrets.yaml
[helm-secrets] Decrypting ./secrets.yaml
config file not found and no keys provided through command line options
[helm-secrets] Error while decrypting file: ./secrets.yaml
Error: plugin "secrets" exited with error
```

### Environment

- Helm Version: v3.7.0
- Helm Secrets Version: 3.12.0-dev
- OS: Ubuntu 20.04
- Shell: bash

**Comment by jkroepke** [comment]
Take a look here https://github.com/mozilla/sops#encrypting-using-age

you can use the environment variable `SOPS_AGE_KEY_FILE=/home/user/.config/sops/keys.txt`

Instead using `-a "--age xx"`, you can also use `SOPS_AGE_RECIPIENTS=xx` als additional environment variable.

```bash
export SOPS_AGE_KEY_FILE=/home/user/.config/sops/keys.txt
export SOPS_AGE_RECIPIENTS=xx
helm secrets dec ./secrets.yaml
```
For helm install, helm upgrade, you can use something like this:

```
helm install release chart -f secrets+age-import:///home/user/.config/sops/keys.txt?secrets.yaml
```
