### ISSUE TITLE
Typos in Argo CD integration wiki

### ISSUE THREAD

**Issue by wilinger** [jkroepke/helm-secrets#180]
### Current Behavior

Just wanted to point out a couple of typos going through the Argo CD Integration wiki.

[ArgoCD%20Integration.md?plain=1#L152](https://github.com/jkroepke/helm-secrets/blob/785222e6316128178eedd765b771f5547a6a6eb6/docs/ArgoCD%20Integration.md?plain=1#L152)
```
gpg --armor --export-key <key-id> > key.asc
```
`--export-key` should be `--export-secret--key`

[ArgoCD%20Integration.md?plain=1#L243](https://github.com/jkroepke/helm-secrets/blob/main/docs/ArgoCD%20Integration.md?plain=1#L243)
```bash
kubectl auth can-i get secrets --namespace argo-cd --as system:serviceaccount:$NAMESPACE:argo-cd-argocd-repo-server
```
Service account name `argo-cd-argocd-repo-server` should be `argocd-repo-server` based on the example service account created.
Also using $NAMESPACE environment variable when already referencing argo-cd as namespace in the same line.

### Environment

- Helm Version:
- Helm Secrets Version:
- OS:
- Shell:

**Comment by jkroepke** [comment]
btw. the wiki is synced with the code repository https://github.com/jkroepke/helm-secrets/blob/main/docs/ArgoCD%20Integration.md

In case, there are more typo, You can create a PR to fix all the findings.
