### ISSUE TITLE
Check for changes in external values

### ISSUE THREAD

**Issue by 171koinoyokan171** [jkroepke/helm-secrets#182]
### Problem Statement

I've modified ArgoCD installation and used workaround to use external values.

> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: app
> spec:
>   source:
>     helm:
>       valueFiles:
>         # if AWS KMS or GCP is used
>         - secrets://https://raw.githubusercontent.com/org/repo/ref/pathtofile.yml

It works, but if I change remote file - it won't trigger ArgoCD sync. Does anyone tried to resolve this issue? 

### Environment

- Helm Version: 3.7.1
- Helm Secrets Version: 3.11.0
- ArgoCD: v2.2.2

**Comment by jkroepke** [comment]
Hi, normally https://github.com/argoproj/argo-cd is would be a better place to discuss this.

Anyway, from what I know ArgoCD have a cache based on git ref. By default ArgoCD caches this 24h. Below the link how to adjust this cache: https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-repo-server/#synopsis

Additionally, ArgoCD have a default sync interval of 3m. For example by reduce the cache expiration, ArgoCD will fetch the external resources.
