### ISSUE TITLE
Does helm secrets uninstall exist?

### ISSUE THREAD

**Issue by jaythamke** [jkroepke/helm-secrets#187]
Hi Jan,
I would like to know if `helm secrets uninstall ...` command exists and does it make sense to uninstall the helm chart using `secrets` plugin from K8s cluster if I already have installed helm chart (with sops encrypted files) using `helm secrets upgrade ...` ? 
Thanks and best regards,
Jayesh

**Comment by jkroepke** [comment]
Hi @jaythamke 

from helm secrets perspective, all unknown commands are just passed to helm.

In fact, `helm secrets uninstall` exists and works. but in this case, helm secrets will call `helm uninstall`. 

It exists, but it wont make any sense to use `helm secrets uninstall.`
