### ISSUE TITLE
Using helm-secrets on Windows

### ISSUE THREAD

**Issue by Hendrik-LGLN** [jkroepke/helm-secrets#195]
### Current Behavior

When I try to execute any `helm secrets` command from Powershell or Windows CMD I get the following error:
`/bin/bash: $HELM_PLUGIN_DIRhelmsecretsscriptsrun.sh: No such file or directory
Error: plugin "secrets" exited with error`

### Expected Behavior

helm-secrets-Commands should work after installing the plugin and probably use run.cmd on Windows instead of run.sh.

### Steps To Reproduce

```markdown
1. Download sops, rename to sops.exe and put it in C:\Windows\system32
2. Install helm-secrets: helm plugin install https://github.com/jkroepke/helm-secrets --version v3.12.0
3. Try to execute any helm secrets command
```

### Environment

- Helm Version: 3.7.2
- Helm Secrets Version: 3.12.0
- OS: Windows 10 Pro 21H2
- Shell: CMD or Powershell

**Comment by jkroepke** [comment]
Looks like something is wrong here.
https://github.com/jkroepke/helm-secrets/blob/b4458dc43f146f121a274b2d011e7305d7f5e58a/plugin.yaml#L10

Are you able to modify your `plugin.yaml` locally after installation?

If yes, can you replace

```
platformCommand:
  - os: windows
    command: "cmd /c $HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd $HELM_PLUGIN_DIR\\scripts\\run.sh"
```

with 

```
platformCommand:
  - os: windows
    command: 'cmd /c $HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd "%HELM_PLUGIN_DIR%/scripts/run.sh"'
```

I currently have no access to a local windows machine, but the CI provides a Windows system. Maybe I have to try it there.

**Comment by jkroepke** [comment]
I tried to reproduce the issue on the CI, but I'm unable to reproduce the issue.

```
helm plugin install https://github.com/jkroepke/helm-secrets
helm secrets -v
```

works both from Powershell Core.

https://github.com/jkroepke/helm-secrets/runs/5302794756?check_suite_focus=true

**Comment by Hendrik-LGLN** [comment]
Tried replacing the content of plugin.yaml but still the same issue. The output of where.exe is `C:\Windows\System32\bash.exe`.

**Comment by jkroepke** [comment]
This is the WSL related bash.exe, right?

One more question, is this true that
* You do not have installed Cygwin on you system
* You do not have installed [Git for Windows](https://gitforwindows.org/) OR it's installed in a non default location?


If both is true, maybe there is a issue around translating paths for WSL.

https://github.com/jkroepke/helm-secrets/blob/b4458dc43f146f121a274b2d011e7305d7f5e58a/scripts/wrapper/sh.cmd#L98-L108

**Comment by Hendrik-LGLN** [comment]
I suppose it is the WSL bash.exe, at least I do have WSL installed. How can I find out if it is the WSL related bash?

I do not have Cygwin installed but I do have Git for Windows in the default location (C:\Program Files).

**Comment by jkroepke** [comment]
> How can I find out if it is the WSL related bash?

Running 
```
> bash.exe -c uname
Linux
```

Thats confirms a Linux context which is only available inside WSL.

**Comment by Hendrik-LGLN** [comment]
Yep, returning Linux. So bash.exe seems to be pointing to WSL. Also tried executing
`bash -c uname` which also returns Linux. So maybe the script will take the jump on line 15 and execute in WSL without adapting the paths?

**Comment by jkroepke** [comment]
Yes correct. 

Look at https://docs.microsoft.com/de-de/windows/wsl/basic-commands#deprecated-wsl-commands, call bash.exe with wsl.exe is deprecated from Microsoft side.

To solve that issue, I prioritize the dection of WSL to the top. Additionaly there was still any error while converting the paths from windows to wsl.

Can you copy the content from linked [sh.cmd](https://github.com/jkroepke/helm-secrets/blob/run-helm-without-bats/scripts/wrapper/sh.cmd) and override the `scripts/wrapper/sh.cmd` on your machine?

You can take a look [here](https://github.com/jkroepke/helm-secrets/pull/196/files), if you are interest into the changes.

**Comment by Hendrik-LGLN** [comment]
The path looks correct now in the error message, but still the error "no such file" does remain although I can see the script at the location it prints.

**Comment by jkroepke** [comment]
What is the command that you execute?

In line 2 of sh.cmd, can you write @echo on to gain some debug output? Is the possible to share it?

**Comment by Hendrik-LGLN** [comment]
Tried `helm secrets -v` which gives the following output:
`C:\Users\USERNAME\Desktop\Project>if not "" == "" GOTO :ENVSH
C:\Users\USERNAME\Desktop\Project>wsl bash -c exit   1>nul 2>&1
C:\Users\USERNAME\Desktop\Project>IF 0 EQU 0 GOTO :WSL
C:\Users\USERNAME\Desktop\Project>SET ARGS=
C:\Users\USERNAME\Desktop\Project>if "\"C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh\""
== "" goto ENDLOOP
C:\Users\USERNAME\Desktop\Project>SET STR1="\"C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh\""
C:\Users\USERNAME\Desktop\Project>if not "x""C:UsersUSERNAMEAppDataRoaminghelmpluginshelm-secrets/scripts/run.sh""" == "x"\"C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh\""" (FOR /F "tokens=* USEBACKQ" %F IN (`wsl wslpath "\"C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh\""`) DO (SET WSLPATH=%F ) )  else (SET WSLPATH=\"C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh\" )
C:\Users\USERNAME\Desktop\Project>(SET WSLPATH="C:/Users/USERNAME/AppData/Roaming/helm/plugins/helm-secrets/scripts/run.sh" )
C:\Users\USERNAME\Desktop\Project>SET ARGS= "C:/Users/USERNAME/AppData/Roaming/helm/plugins/helm-secrets/scripts/run.sh"
C:\Users\USERNAME\Desktop\Project>shift
C:\Users\USERNAME\Desktop\Project>goto LOOP
C:\Users\USERNAME\Desktop\Project>if "-v" == "" goto ENDLOOP
C:\Users\USERNAME\Desktop\Project>SET STR1="-v"
C:\Users\USERNAME\Desktop\Project>if not "x"-v"" == "x"-v"" (FOR /F "tokens=* USEBACKQ" %F IN (`wsl wslpath "-v"`) DO (SETET WSLPATH=%F ) )  else (SET WSLPATH=-v )
C:\Users\USERNAME\Desktop\Project>SET ARGS= "C:/Users/USERNAME/AppData/Roaming/helm/plugins/helm-secrets/scripts/run.s.sh" -v
C:\Users\USERNAME\Desktop\Project>shift
C:\Users\USERNAME\Desktop\Project>goto LOOP
C:\Users\USERNAME\Desktop\Project>if "" == "" goto ENDLOOP
C:\Users\USERNAME\Desktop\Project>wsl bash  "C:/Users/USERNAME/AppData/Roaming/helm/plugins/helm-secrets/scripts/run.s.sh" -v
bash: C:/Users/USERNAME/AppData/Roaming/helm/plugins/helm-secrets/scripts/run.sh: No such file or directory
C:\Users\USERNAME\Desktop\Project>exit /b 127
Error: plugin "secrets" exited with error
PS C:\Users\USERNAME\Desktop\Project>`

**Comment by Hendrik-LGLN** [comment]
Maybe the path has to be adapted even more? When I enter just `wsl bash` it tells me I am on the path `/mnt/c/Users/USERNAME/Desktop/Project`.

**Comment by jkroepke** [comment]
Look like the path transition with wslpath

```
wsl wslpath "C:\Users\USERNAME\AppData\Roaming\helm\plugins\helm-secrets/scripts/run.sh"
```

is not working here.

**Comment by Hendrik-LGLN** [comment]
Yep, that did it. `helm secrets -v`is working now. `helm secrets view ./helm/secrets.yaml` is complaining that it cannot find sops but that seems to be a different issue. We put sops on the Windows path, maybe we need to set some env variable for helm-secrets to find it when using WSL?

**Comment by jkroepke** [comment]
>  We put sops on the Windows path, maybe we need to set some env variable for helm-secrets to find it when using WSL?

Yes, I'm already on it.

https://github.com/jkroepke/helm-secrets/pull/196/files#diff-faecaf69907ff178c28dc34778b935ce14db783415a6e52868753730bf619171R113-R116

**Comment by jkroepke** [comment]
Hi @Hendrik-LGLN ,

can you provide some feedback, if https://github.com/jkroepke/helm-secrets/blob/run-helm-without-bats/scripts/wrapper/sh.cmd works for you?

**Comment by Hendrik-LGLN** [comment]
Seems to be working, thanks a lot for your help!
