### ISSUE TITLE
Run helm-secrets on WSL broke the flow

### ISSUE THREAD

**Issue by daniloraisi** [jkroepke/helm-secrets#197]
### Current Behavior

When running helm-secrets on a WSL environment, it stops with an error:
```bash
/home/danilo/.local/share/helm/plugins/helm-secrets/scripts/run.sh: 37: TEMP: parameter not set
Error: plugin "secrets" exited with error
```

### Expected Behavior

Should run without any error on any environment.

### Steps To Reproduce

```markdown
1. On a WSL Environment
2. Run a Secrets command (e.g., helm upgrade).
3. It stops with the error presented before.
```

### Environment

- Helm Version: 3.8.0
- Helm Secrets Version: main-branch
- OS: Ubuntu 20.04 (WSL)
- Shell: Bash

### Anything else?

I noticed that this error started with PR #196

**Comment by jkroepke** [comment]
Questions:

Are you call helm secrets from powershell or from wsl bash?
Are you using sops? is sops a win32 binary in your setup or still a linux binary inside wsl?

Is wslenv a pre-installed binary?

**Comment by daniloraisi** [comment]
@jkroepke

I'm running the command within WSL Bash.
I'm using SOPS. It's installed as a Linux binary using the right package.

It is a pre-installed binary.
