### ISSUE TITLE
Maintenance status of this fork 

### ISSUE THREAD

**Issue by jkroepke** [jkroepke/helm-secrets#2]
Since [upstream](https://github.com/zendesk/helm-secrets/) looks dead I'll start to maintain a forked version of helm-secrets.

Issues to be fixed here:

- [x] https://github.com/zendesk/helm-secrets/issues/151 (#5)

Issues and pull requests covered by: #1 

* https://github.com/zendesk/helm-secrets/issues/128 (name of secret more relaxed)
* https://github.com/zendesk/helm-secrets/issues/141 (name of secret more relaxed)
* https://github.com/zendesk/helm-secrets/pull/149
* https://github.com/zendesk/helm-secrets/pull/150
* https://github.com/zendesk/helm-secrets/pull/129 (All name restrictions dropped)
* https://github.com/zendesk/helm-secrets/pull/143
* https://github.com/zendesk/helm-secrets/pull/142 (dpkg variant dropped; you should never run helm plugin install as root)
* https://github.com/zendesk/helm-secrets/pull/136 (verbose output is not on stderr)

**Comment by jkroepke** [comment]
See also: https://github.com/jkroepke/helm-secrets/blob/master/CHANGELOG.md

**Comment by dminkovsky** [comment]
I am wondering: why is the upstream designed "deprecated"? Did Zendesk not want to allocate resources to maintaining the project, or is it actually deprecated in the sense that there is some new, better way to manage secrets with Helm?

**Comment by jkroepke** [comment]
> Did Zendesk not want to allocate resources to maintaining the project

I guess thats the reason, because they didn't use helm-secrets anymore.

See: https://github.com/zendesk/helm-secrets/pull/168

**Comment by dminkovsky** [comment]
I see. Thanks a lot.
