### ISSUE TITLE
argo cd failing to sync with helm-secrets remote uri path

### ISSUE THREAD

**Issue by jmclean-starburst** [jkroepke/helm-secrets#203]
### Current Behavior

this is a weird one....

im getting the below error in ArgoCD, which only happens for apps that are leveraging `secrets://https://` prefix in the helm application manifest CR. this is only happening for me in one environment, i have deployed 3 others successfully w/ the above pattern.

```
failed exit status 2: curl: (22) The requested URL returned error: 404 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813b98] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile({0xc00011e210, 0x100000000000007}, {0xc000430200, 0x3, 0x4}) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0001159e0, {0xc000430200, 0xc00081f9f8, 0xc0001d2080}) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385 main.runInstall({0xc000299000, 0xc00063fa98, 0xc00063fac0}, 0xc0003aa420, 0xc0005ac540, {0x1f67d00, 0xc0001ae008}) helm.sh/helm/v3/cmd/helm/install.go:198 +0x385 main.newTemplateCmd.func2(0xc00045d900, {0xc000299000, 0x1, 0x15a}) helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a github.com/spf13/cobra.(*Command).execute(0xc00045d900, {0xc000297800, 0x15a, 0x180}) github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e9680) github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.3.0/command.go:902 main.main() helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234
```

### Expected Behavior

helm template doesnt fail

### Steps To Reproduce

```markdown
not sure :(
```

### Environment

- Helm Version: not sure - whatever is baked into ArgoCD
- Helm Secrets Version: 3.12.0
- OS: ArgoCD v2.3.0
- Shell: ArgoCD v2.3.0

**Comment by jkroepke** [comment]
> curl: (22) The requested URL returned error: 404

curls reports that the URL does not exists.

> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813b98] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile({0xc00011e210, 0x100000000000007}, {0xc000430200, 0x3, 0x4}) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0001159e0, {0xc000430200, 0xc00081f9f8, 0xc0001d2080}) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385 main.runInstall({0xc000299000, 0xc00063fa98, 0xc00063fac0}, 0xc0003aa420, 0xc0005ac540, {0x1f67d00, 0xc0001ae008}) helm.sh/helm/v3/cmd/helm/install.go:198 +0x385 main.newTemplateCmd.func2(0xc00045d900, {0xc000299000, 0x1, 0x15a}) helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a github.com/spf13/cobra.(*Command).execute(0xc00045d900, {0xc000297800, 0x15a, 0x180}) github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e9680) github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.3.0/command.go:902 main.main() helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234

This is a follow up issue related to helm: https://github.com/helm/helm/issues/10685

**Comment by jmclean-starburst** [comment]
I noticed the curl response...the problem is that all of this was working w/ ArgoCD v2.1.5, but the upgrade to ArgoCD v2.3.0 borked this; i didnt change the remote URI references

**Comment by jmclean-starburst** [comment]
i found my issue, the `${GITHUB_TOKEN}` value i use in the URI was misconfigured
