### ISSUE TITLE
encrypting empty file gives panic error

### ISSUE THREAD

**Issue by Morriz** [jkroepke/helm-secrets#209]
### Current Behavior

As the title says. It is a SOPS bug, but the maintainers are not responsive, and I see you are willing to help out.

Would it be much work to check if a file is empty before operating on it with sops? It is probably 3 lines of code for you, and then we can all rely on a robust solution for file encryption. Hopefully the peeps at mozilla behind SOPS realize soon that it should be fixed on their end after that.

Letting userland sort this out is not right, don't you agree?

Ref SOPS issues open because of this:
- https://github.com/mozilla/sops/issues/483
- https://github.com/mozilla/sops/issues/748

### Expected Behavior

no panic

### Steps To Reproduce

```markdown
try to encrypt an empty file
```

### Environment

- Helm Version: 3.8.1
- Helm Secrets Version: 3.12.0
- OS:
- Shell:

**Comment by jkroepke** [comment]
Hi,

sure, I'm open to workarounds until the issue the resolved upstream.

Currently, I'm not sure how I could detect an empty YAML without add an additional dependency to an external tool which I want to avoid. But Pre-installed tools like sed, tr are fine.

Sure, I can check for `""` but reading https://github.com/mozilla/sops/issues/748: File just contains commentary are also affected.

**Comment by jkroepke** [comment]
If you have a proposal to solve the issue, feel free to add a PR, including tests. GH actions runs on multiple platform to ensure that it still works.

**Comment by jkroepke** [comment]
Hey @Morriz 

I'm unable to reproduce the error here. Did you ever check, if the error exists in the current version of helm secrets?

Look at 

https://github.com/jkroepke/helm-secrets/blob/ace987a7a0244aae5f2b3ed371513d283c96dd8b/scripts/drivers/sops.sh#L11-L15

sops is only executed, if the file contains `sops` and `gcp_kms`. On an empty file, helm-secrets wont call `sops`.

**Comment by Morriz** [comment]
Ah, tnx...I see it is release in the latest `3.13.0` from 3 days ago. Just missed that ;)

**Comment by jkroepke** [comment]
> from 3 days ago.

Strictly, the code in already 2 years old.

https://github.com/jkroepke/helm-secrets/commit/00fa30633ea0218d296a51ad03299e218a73dfa3#diff-d8cf3e1154580eeb40b1cb00f3a7468885b2ae70068f06cf655e96f59e7d7aebR1-R8

https://github.com/zendesk/helm-secrets is still affected by this issue.

**Comment by Morriz** [comment]
strange...we are using `3.12.0` but get errors on empty files. The fix is not in there then I presume.
