### ISSUE TITLE
Running on windows and using vals doesn't work

### ISSUE THREAD

**Issue by sherifkayad** [jkroepke/helm-secrets#223]
### Current Behavior

Performing some helm command on Windows e.g.:
```bash
helm secrets upgrade --install my-release --namespace=my-namespae -f values.yml -f secrets.yml some/chart --version="some.version" --dry-run
```

I would get:
```bash
/mnt/host/c/Users/myuser/AppData/Roaming/helm/plugins/helm-secrets/scripts/drivers/vals.sh: line 12: vals: command not found
[helm-secrets] Error while decrypting file: secrets.yml
Error: plugin "secrets" exited with error
```

### Expected Behavior

Things to work smoothly.

### Environment

- Helm Version: `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}`
- Helm Secrets Version: `3.14.0-dev`
- OS: `Windows`
- Shell: `MINGW`

**Comment by jkroepke** [comment]
Is `vals` in your PATH? Are you able to call `vals` from cmd? Are you able to call `vals` from MINGW shell?

**Comment by sherifkayad** [comment]
Yes, sure it's. I can run `vals` directly from both cmd and MINGW e.g. something like `vals eval -f secrets.yml` works great

**Comment by jkroepke** [comment]
Do you have wsl installed on your system?

**Comment by sherifkayad** [comment]
yes I have WSL2 installed and enabled. Running from MINGW with the bvariable you suggested doesn't work.

**Comment by jkroepke** [comment]
> Running from MINGW with the bvariable you suggested doesn't work.

To reproduce the error, what did you try? What is the error? Can you re-rerun your command with `helm --debug secret upgrade ...` and share the output here?

**Comment by sherifkayad** [comment]
setting the variable `HELM_SECRETS_WINDOWS_SHELL` to the value of the path of my `bash.exe` e.g. `/user/bin/bash.exe` results in the following with `helm secrets upgrade .. --debug`:
```bash
Files/Git/usr/bin/bash.exe]==[] was unexpected at this time.
Error: plugin "secrets" exited with error
helm.go:84: [debug] plugin "secrets" exited with error
```

**Comment by sherifkayad** [comment]
the fix you provided with https://github.com/jkroepke/helm-secrets/commit/a498ef063c28e3015bd50d9e3b74758ef7fc9143 works like a charm! I had to unset back the `HELM_SECRETS_WINDOWS_SHELL` to nothing

**Comment by jkroepke** [comment]
Patchs are in main now. WSL2 or a custom shell through env var should work now.
