### ISSUE TITLE
Multiline secrets not behaving correctly with helmfile and vault driver

### ISSUE THREAD

**Issue by JonasJR** [jkroepke/helm-secrets#229]
### Current Behavior

We are using helm-secrets with the vault driver to get secrets from our hashicorp vault. On top of that we are using helmfile. The problem I have is to get the multi row secrets (such as certificates) to be handled correctly.

I have a secrets.yaml file:
```
db:
  clientCert: !vault secret/certs#clientCert
```
But I get the error: 
```Error converting YAML to JSON: yaml: line 2: could not find expected ':'```
Probably because the file the looks like this:
```
db:
  clientCert: -----BEGIN CERTIFICATE-----
blablabla
balbalblalb
balblablbbal
-----END CERTIFICATE-----
```
 I have also tried the following:
```
db:
  clientCert: |
    !vault secret/certs#clientCert
```
To get: 
```
db:
  clientCert: |
    -----BEGIN CERTIFICATE-----
    blablabla
    balbalblalb
    balblablbbal
    -----END CERTIFICATE-----
```
But I instead get:
```Error converting YAML to JSON: yaml: unknown anchor 'helm-secret-secret_certs_clientCert' referenced```

### Expected Behavior

When I do:
```
db:
  clientCert: |
    !vault secret/certs#clientCert
```

I should get:
```
db:
  clientCert: |
    -----BEGIN CERTIFICATE-----
    blablabla
    balbalblalb
    balblablbbal
    -----END CERTIFICATE-----
```

### Steps To Reproduce

```markdown
1. Add certificate to kv store in Hashicorp vault
2. Create secret.yaml with:
db:
  clientCert: !vault secret/certs#clientCert
3. Run helmfile diff
```

### Environment

- Helm Version: v3.7.2
- Helm Secrets Version: 3.13.0
- OS: Ubuntu 20.04
- Shell: tested in bash and zsh (different hosts)

**Comment by jkroepke** [comment]
Sounds strange. In the test suite, this case is already coved and works fine:

Here is the test:

Vault values:

https://github.com/jkroepke/helm-secrets/blob/0f5ceb51f57c03311241f3c06bbc554a8b4752a5/tests/assets/values/vault/seed.sh#L8-L25

Secret:

https://github.com/jkroepke/helm-secrets/blob/0f5ceb51f57c03311241f3c06bbc554a8b4752a5/tests/assets/values/vault/secrets.yaml#L1-L13

Running `HELM_SECRETS_DRIVER=vault helm secrets view tests/assets/values/vault/secrets.yaml` locally results into this:

```yaml
.helm-secret-secret___test-example_com_tls_key: &helm-secret-secret___test-example_com_tls_key key2

.helm-secret-secret_domain___test-example_com: &helm-secret-secret_domain___test-example_com key1

.helm-secret-secret_domain_example_com: &helm-secret-secret_domain_example_com key1

.helm-secret-secret_domain_tls_crt: &helm-secret-secret_domain_tls_crt tls.value

.helm-secret-secret_example_com_tls-2_key: &helm-secret-secret_example_com_tls-2_key key2

.helm-secret-secret_gpg_key: &helm-secret-secret_gpg_key |-
  -----BEGIN PGP MESSAGE-----

  wcFMAxYpv4YXKfBAARAAVzE7/FMD7+UWwMls23zKKLoTs+5w9GMvugn0wi5KOJ8P
  PSrRY4r27VhwQH38gWDrzo3RCmO9414xZ0JW0HaN2Pgd3ml6mYCY/5RE7apgGZQI
  3Im0fv8bhIwaP2UWPp74EXLzA3mh1dUtwxmuWOeoSq+Vm5NtbjkfUt/4MIcF5IAY
  c+U4ZOdQlzgExwu+VtOpeBrkwfglh5fFuKqM8Fg1IICi/Pp6YAlpAdGqlt1zS4Pj
  yjAS6eAvnpM0eA5hShuoO9JsAu4kVjaaBlipVpc1I2zdcT3H/1d7ASziwbKOm6jE
  PJxzaMDxn0UfMjkhTaTZ8v27lz6W7qdlHdCWGGI348QkSoDotm7OzMC7ZLfps3+9
  GrXo9Kwxkj6oy/thn92W2cRSeSD28g6kcUkHeG8L3mMv+gpTjIhM+Z8x3jJcVp2i
  yoA2dO/kO2/HTcUfnEjppKigqUlRuKfDn8ercjYiq+foqtimH192iXXyRmltYlH0
  GUSJ1FcNLAC9g0WLFPQnMFh5KxSweavpbdd6PILqEsyKvZpC5a+hzLKwGjWOveW1
  K34QZf6Ay3CPCegAyGVjxmsg1vPKD+9WAZinveCl37l3cCQW1VZzbGkHgtLQ30Qr
  DCRFZEstraLAQUf6VLAk9bPYX/fvkXmra970i/CfJjIg0SpOXbADBR4x+zRRZqrS
  4AHkWTmhH/xXWyAgmh+sGs18OOFGfeC04AjhMmvg4uKzly6+4IDlNhPif2VpJYOi
  EmU8gQoUsAHKYro0hPfzBZyJlL+TqCPgHeRPANVgm4Ww6RlVrNFpTy9H4m4s5y/h
  EzAA
  =jf7D
  -----END PGP MESSAGE-----

.helm-secret-secret_production_data: &helm-secret-secret_production_data
  global_secret: global_bar
  port: "81"
  port2: "83"
  
.helm-secret-secret_production_global_secret: &helm-secret-secret_production_global_secret global_bar

.helm-secret-secret_production_port: &helm-secret-secret_production_port "81"

global_secret: *helm-secret-secret_production_global_secret
key: *helm-secret-secret_gpg_key
service:
  port: *helm-secret-secret_production_port
data: *helm-secret-secret_production_data
domain:
  cert: *helm-secret-secret_domain_tls_crt
  names:
    - *helm-secret-secret_domain___test-example_com
    - *helm-secret-secret_domain_example_com
  keys:
    - *helm-secret-secret___test-example_com_tls_key
    - *helm-secret-secret_example_com_tls-2_key
```

The generated yaml files looks a little bit odd and messy, but it resolves a lot of escape trouble.

Seems like there are multiple ways to store multiline data and I do not cover all.


@JonasJR 

1. Are you able to test #230, if this help for you?
  ```bash
  helm plugin install https://github.com/jkroepke/helm-secrets --version vault-multiline
  ```
2. This there a way how I could reproduce it? I would like to have an test case for this...

**Comment by JonasJR** [comment]
I had to move on due to tight schedule and solved this in another way. I'm sorry if I wasted your time, but I think that the issue must have been in another part of my pipeline (read helmfile)

**Comment by jkroepke** [comment]
Thanks for the short comment. Then I will close it.
