### ISSUE TITLE
Helm secrets is slow on WSL

### ISSUE THREAD

**Issue by joelee2012** [jkroepke/helm-secrets#231]
### Current Behavior

run `helm secrets` on wsl is very slow

### Expected Behavior

work normal

### Steps To Reproduce

```markdown
run `helm secrets -h`
```

### Environment

- Helm Version:v3.8.2
- Helm Secrets Version: 3.13.0
- OS: wsl ubuntu 20.04
- Shell: bash

### Anything else?

the reason is `wslvar TEMP` very slow in run.sh

**Comment by jkroepke** [comment]
Can you take a look at #232, if it fits for you?

Can be installed with:
```bash
helm plugin install https://github.com/jkroepke/helm-secrets.git --version wsl-performance
```

#232 removes wslvar.

**Comment by joelee2012** [comment]
it reports error:
```
/home/joelee/.local/share/helm/plugins/helm-secrets.git/scripts/run.sh: 34: TEMP: parameter not set
Error: plugin "secrets" exited with error
```
version :
```
$ helm plugin list
NAME    VERSION         DESCRIPTION
diff    3.4.2           Preview helm upgrade changes as a diff
secrets 3.14.1-dev      This plugin provides secrets values encryption for Helm charts secure storing
```

**Comment by joelee2012** [comment]
why don't set `TMPDIR=/tmp` ?

**Comment by jkroepke** [comment]
If helm-secrets write the files to `/tmp` and call sops.exe (win32 application), sops.exe would report "file not found" since /tmp is not reachable from windows context...

**Comment by joelee2012** [comment]
why does call sops.exe ? should it be https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64 for wsl ?
i have tested sops-v3.7.3.linux.amd64 with TEMP=/tmp, everything is working fine.

**Comment by jkroepke** [comment]
Does it work, if you are using gpg4win? Not everyone runs the full tool chain inside WSL.

**Comment by joelee2012** [comment]
i'm not sure, but refer: https://www.gpg4win.org/system-requirements.html, GnuPG is for wsl/linux

**Comment by jkroepke** [comment]
Do not forget that WSL is also used in the background, if helm secrets is called from a powershell (or any other win32 shell). Thats why a win32 application interoperability is required.

Long term, I want to avoid temp files completly. Currently helm does not supporting to pass multiple files through stdin https://github.com/helm/helm/pull/10867.

**Comment by joelee2012** [comment]
i agree with you and i will comment the line in my local.

**Comment by jkroepke** [comment]
@joelee2012 I do some improvements around the /tmp handling and reading some topics around the WSL win32 interop.

Is it possible that you re-test the #232? I would like to know, if this works for you.

Mention that `TEMP` does not have any effect anymore.

```shell
helm plugin install https://github.com/jkroepke/helm-secrets.git --version wsl-performance
```

**Comment by joelee2012** [comment]
@jkroepke  i can confirm it works perfect, the target file will be in random folder in /tmp, eg `/tmp/tmp.9LybvE1Cld/1030171915/values.yaml ` 👍

**Comment by jkroepke** [comment]
And the performance is acceptable?
