### ISSUE TITLE
Support sops updatekeys behavior when keys are modified in .sops.yaml

### ISSUE THREAD

**Issue by mg-christian-axelsson** [jkroepke/helm-secrets#233]
### Problem Statement

Originally reported in the old repository as https://github.com/zendesk/helm-secrets/issues/147

When `.sops.yaml` have keys added/removed there should be a good way to re-encrypt files with the new keys, similar to `sops updatekeys` (https://github.com/mozilla/sops#updatekeys-command).

### Environment

- Helm Version:
- Helm Secrets Version:
- OS:
- Shell:

**Comment by jkroepke** [comment]
> sops doesn't like accept with non-standard filenames like cluster.rkestate without forcing the format while helm secret does (by assuming yaml I guess).

helm secrets is not more than a wrapper around sops and alternatives. helm secrets forces YAML with `sops --input-type yaml --output-type yaml`.


Not sure, if `sops updatekeys --input-type yaml --output-type yaml cluster.rkestate` helps you.
