### ISSUE TITLE
config file not found and no keys provided through command line options

### ISSUE THREAD

**Issue by djjudas21** [jkroepke/helm-secrets#242]
### Current Behavior

When I try to encrypt a new secret with `helm secrets enc`, using sops+age, it fails with the below error:

```
[jonathan@poseidon kubernetes-manifests]$ helm secrets enc smtp/creds.yaml
Encrypting smtp/creds.yaml
config file not found and no keys provided through command line options
Error: plugin "secrets" exited with error
```

### Expected Behavior

I expect it to encrypt the secret. This worked in the past, and I haven't knowingly changed anything on my system but it's been a while since I have added a new secret. I am still able to decrypt secrets, e.g.

```
[jonathan@poseidon kubernetes-manifests]$ helm secrets view owncloud/creds.yaml
ownCloud:
    adminUsername: [redacted]
    adminPassword: [redacted]
```

### Steps To Reproduce

Full steps I ran to set this up, which I documented:

```markdown
sudo dnf install age
brew install helm sops
helm plugin install https://github.com/jkroepke/helm-secrets --version v3.14.0
mkdir -p ~/.config/sops/age
age-keygen > ~/.config/sops/age/keys.txt
```

I thought placing my age key in `~/.config/sops/age/keys.txt` would be sufficient but just in case I also set `SOPS_AGE_KEY_FILE`

```
[jonathan@poseidon kubernetes-manifests]$ echo $SOPS_AGE_KEY_FILE
/home/jonathan/.config/sops/age/keys.txt

[jonathan@poseidon kubernetes-manifests]$ cat /home/jonathan/.config/sops/age/keys.txt
# created: 2022-05-11T15:27:20+01:00
# public key: age1xeguyqecm3zx2talea7jfawpgzfymula3f9e7cyr76czeh3qdqhs6ap9sp
AGE-SECRET-KEY-1AN[redacted]
```

### Environment

- Helm Version:3.9.2
- Helm Secrets Version: 3.14.0
- OS: Fedora 36
- Shell: bash
- sops: 3.7.3
- age: 1.0.0-5.fc36

### Anything else?

I appreciate this might not be an issue with helm secrets, and is probably sops but I hope you can advise. I have no experience with sops outside of the integration with helm secrets. I've checked the issue trackers of both sops and age, and there was nothing relevant. Thanks.

**Comment by jkroepke** [comment]
sops needs the public key to encrypt the file. In your case, set  `SOPS_AGE_RECIPIENTS=age1xeguyqecm3zx2talea7jfawpgzfymula3f9e7cyr76czeh3qdqhs6ap9sp` though env variables.

See also: https://github.com/mozilla/sops#22encrypting-using-age

Looks like `SOPS_AGE_KEY_FILE` is only used on decryption.

**Comment by djjudas21** [comment]
Thanks, adding this has fixed my problem. This is strange because I never knowingly set it, so maybe sops has changed its behaviour.
