### ISSUE TITLE
Multiple values in a single --set option not correctly passed to helm

### ISSUE THREAD

**Issue by Ari-H** [jkroepke/helm-secrets#273]
### Current Behavior

helm `--set` option supports passing multiple values:
```
--set stringArray              set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
```

This worked still in helm secrets v4.0.0, but after the changes in v4.1.0 the values are not passed correctly.

`--set key1=val1,key2=val2` results in the following key-value being used for the helm command:

- key1: "val1,key2=val2"

### Expected Behavior

`--set key1=val1,key2=val2` should result in the following key-values being used for the helm command:

- key1: "val1"
- key2: "val2"

### Environment

- Helm Version: 3.4.1
- Helm Secrets Version: 4.1.1
- OS: Alpine Linux v3.16
- Shell: GNU bash, version 5.1.16

**Comment by jkroepke** [comment]
I see.. current workaround around is `--set key1=val1 --set key2=val2`
