### ISSUE TITLE
Secrets are not created when upgrading an existant release

### ISSUE THREAD

**Issue by TheoGthr** [jkroepke/helm-secrets#278]
### Current Behavior

We have an existing release `X` deployed on a cluster without the helm-secrets plugin. We encrypted our secrets with the plugin in a new file `secrets.yaml`, and then tried to upgrade our already deployed release with these two commands:

```bash
# Dry run
helm secrets upgrade --install --cleanup-on-fail --dry-run --namespace ${KUBE_NAMESPACE} --values environments/values-test.yaml --values environments/secrets.yaml --set image.version="${APP_VERSION}" ${APPNAME} ./ 1> /dev/null
# Upgrade
helm secrets upgrade --install --cleanup-on-fail --timeout=30m --wait --namespace ${KUBE_NAMESPACE} --values environments/values-test.yaml --values environments/secrets.yaml --set image.version="${APP_VERSION}" ${APPNAME} ./
```

The decryption is successful, but the secrets are not created and therefore our release deployments ends in a failed state, with pods firing these events: `secret mysecret not found`. When we play `helm uninstall ${APPNAME}`, and then execute these two commands again, the secrets are deployed and the release works fine.

### Expected Behavior

When I upgrade with helm-secrets an existing release deployed without the helm-secrets plugin, all the secrets are deployed and used by the deployed pods.

### Environment

- Helm Version: 3.9.2
- Helm Secrets Version: 3.14.0
- OS: Alpine
- Shell: bash 5.1

**Comment by jkroepke** [comment]
This seems not helm secrets related. Verify. that the secrets in your helm chart does not contain conditions like

`{{- if .Release.IsInstall }}`

**Comment by TheoGthr** [comment]
The secrets only have these annotations:

```yaml
metadata:
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: "pre-install,pre-upgrade"
```

We do not have this issue when we upgrade our releases without the helm-secrets plugin, that is why I am looking into that direction.

**Comment by jkroepke** [comment]
If you run `helm secrets template`, can you confirm that the Secret resources are included?

Whats the reason for having the secret inside a `helm.sh/hook-weight` ?

**Comment by TheoGthr** [comment]
Yes, the Secrets are included when I run helm secrets template

I do not know, I do not have the whole history of the project. But we can try removing this hook and try deploying the release again.

**Comment by TheoGthr** [comment]
Removing the hook annotation does not affect the deployment of the release: on an environment installed without helm secrets, we are not able to deploy a new release.
