### ISSUE TITLE
Patch windows command not working

### ISSUE THREAD

**Issue by semezza** [jkroepke/helm-secrets#279]
### Current Behavior

When running `helm secrets patch windows` as specified in the readme.md with version 3.12.0 (as stated as latest stable version in installation readme) I get the error:
Error: unknown command "patch" for "helm"

The command is also not present within the help menu of the plugin

### Expected Behavior

I am able to use helm secrets on a windows machine

### Steps To Reproduce

```markdown
1. On a windows machine, execute `helm plugin install https://github.com/jkroepke/helm-secrets --version v3.12.0`
2. Execute `helm secrets patch windows`
```

### Environment

- Helm Version: 3.9.3
- Helm Secrets Version: 3.12.0
- OS: Windows
- Shell: Powershell

**Comment by jkroepke** [comment]
Okay. `3.12.0` is not the latest version. The value in the documentation seems outdated.

4.1.1 is the latest version. Looking at Changelog, helm secrets patch is available in 3.14.0 or higher
