### ISSUE TITLE
Helm 3 Issues Running in CloudBuild in GCP to Access Secrets Manager secrets

### ISSUE THREAD

**Issue by sephethus** [jkroepke/helm-secrets#280]
### Current Behavior

I got directed to helm-secrets by the Google documentation for Secrets Management in CI/CD.

When I do this command inside a docker container in GCP cloudbuild as an attempt to use Google Secrets Manager based secrets as vaguely outlined with no examples in the documentation:

`helm secrets upgrade --wait --timeout 1000s --install --debug --create-namespace \
          --values=./helm/values.$PROJECT_ID.yaml \
          --set app_centers="{$app_centers}" \
          --set job_app_centers="{$app_centers}" \
          --set image.tag=$REVISION_ID \
          --set asset.hostname=storage.googleapis.com/$PROJECT_ID-assets/$REVISION_ID \
          --set environment=$environment \
          --set namespace="prism-$environment" \
          --set redis_uri="$redis_uri" \
          --namespace="prism-$environment" \
          "prism-$environment" \
          ./helm`

It does this:

`unknown command "secrets" for "helm"`

The plugin is installed, I tested it within the docker image with docker run. It's there, it works. I don't know why it is lying about secrets not being a known command unless that is a misleading error message.

### Expected Behavior

It should at least know the plugin is installed, because it is, and shouldn't give me that error. It should continue with a normal upgrade command.

### Steps To Reproduce

```markdown
1. Run a helm secrets upgrade --install command like the above within a docker image that has both helm 3 and the plugin installed... all within cloudbuild.
2. Watch the error happen.
```

### Environment

- Helm Version: 3.10
- Helm Secrets Version: 4.x (latest I'm sure)
- OS: Alpine docker image
- Shell: sh

**Comment by jkroepke** [comment]
Can you share the documentation?

**Comment by jkroepke** [comment]
> The plugin is installed, I tested it within the docker image with docker run. 

helm plugins are by default inside the user directory. It could be possible that CloudBuild thats the image with an different user.

define the environment variable HELM_DATA_HOME before installing helm may helps here.

**Comment by sephethus** [comment]
Helm should be installed to /usr/local/bin in this case as that is where it seems to go based on the installation, but I'll try this.

**Comment by jkroepke** [comment]
You can validate this by running `helm env` inside the docker container and inside CloudBuild. If the output is difference, that cloud be the reason why the plugin is not found. Yes. helm is in /usr/local/bin which is fine, but helm plugin install will put all additional file into the users home directory.

**Comment by sephethus** [comment]
I repointed it to /usr/local/bin instead so helm env says that's what it is set to now. Yet cloudbuild still throws the same error.

**Comment by sephethus** [comment]
I set it back to default by removing the environment variable again and it's set to HELM_DATA_HOME="/root/.local/share/helm"

**Comment by sephethus** [comment]
I rebuilt the docker image from scratch --no-cache with both those environment variables set after helm is installed but before the plugin. For example:

`# Install helm 3
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh

ENV HELM_DATA_HOME=/usr/local/bin
ENV HELM_PLUGINS=/usr/local/bin

# Install GKE plugin
RUN gcloud components install gke-gcloud-auth-plugin

# Install helm-secrets
RUN helm plugin install https://github.com/jkroepke/helm-secrets`


It worked!

**Comment by sephethus** [comment]
I'm still looking for the documentation that led me here from Google, I'll trace my steps back.
