### ISSUE TITLE
Path error on Windows

### ISSUE THREAD

**Issue by itscaro** [jkroepke/helm-secrets#281]
### Current Behavior

```
helm secrets decrypt C:\Users\qtran\workspace\...\_secrets.yaml
[helm-secrets] File does not exist: C:Usersqtranworkspace..._secrets.yaml
Error: plugin "secrets" exited with error
```

```
secrets         4.1.1   This plugin provides secrets values encryption for Helm charts secure storing
```

I still need to use
```
$env:HELM_SECRETS_WINDOWS_SHELL="C:/Users/qtran/scoop/shims/git-bash.exe"
```

With busybox
```
$env:HELM_SECRETS_WINDOWS_SHELL="C:/Users/qtran/scoop/shims/bash.exe"
```
I have
```
cat: can't open '/dev/stdin': No such file or directory
  [helm-secrets] File is not encrypted: C:\Users\qtran\workspace\...\_secrets.yaml
  Error: plugin "secrets" exited with error
```

Thanks

### Environment

- Helm Version: 3.10.1
- Helm Secrets Version: 4.1.1
- OS: Windows 11
- Shell: pwsh + busybox

**Comment by jkroepke** [comment]
Hi @itscaro 

thats expected. The git bash based in mingw64, while busybox does not offer any POSIX abstraction layer.

**Comment by itscaro** [comment]
@jkroepke is it possible to add a check for `git-bash.exe` so that PC with git installed with scoop does not need to manually set the env var?

**Comment by jkroepke** [comment]
Does `%programfiles%\Git\bin\bash.exe` not exists on your side? I'm not 100% familiar with Git for Windows.

**Comment by jkroepke** [comment]
anyway, cloud you test `helm plugin install https://github.com/jkroepke/helm-secrets --version fix/stdin`, if that PR works on busybox? See #282

**Comment by itscaro** [comment]
> Does `%programfiles%\Git\bin\bash.exe` not exists on your side? I'm not 100% familiar with Git for Windows.

No, I do not have Git installed with Git for Windows installer, I have git via scoop, all tools are installed in `$HOME/scoop/shims/`

`$HOME/scoop/shims/bash.exe` for busybox
`$HOME/scoop/shims/git-bash.exe` for git bash

> anyway, cloud you test `helm plugin install https://github.com/jkroepke/helm-secrets --version fix/stdin`, if that PR works on busybox? See #282

This patch makes `busybox` to work well, I prefer `busybox` to `git-bash` in my installation because, git-bash runs helm decrypt in another window and if there are errors, I cannot see the errors in the main terminal.

in $PROFILE, I now set
```
$env:HELM_SECRETS_WINDOWS_SHELL="$HOME\scoop\shims\bash.exe"
```
