### ISSUE TITLE
SOPS YAML files with Windows line-endings (CR LF) not as YAML detected

### ISSUE THREAD

**Issue by PoliM** [jkroepke/helm-secrets#290]
### Current Behavior

We use SOPS with YAML files. When we tried using helm-secrets >= 4.0.0 we were not able to decrypt all secrets. 
Turns out, that since some users use Windows to create the files, their line-endings consist of CR LF. But the mechanism to detect whether it is a YAML, binary or JSON format does not recognize that and thinks it is a JSON, which therefore leads to an unmarshalling error. I have more information bellow under "Anything else".

### Expected Behavior

Detecting the file as YAML and decrypt it.

### Steps To Reproduce

```markdown
- Use a YAML file with CR LF line-endings.
- Try to decrypt it.
```

### Environment

- Helm Version: 3.10.1
- Helm Secrets Version: 4.2.0
- OS:  Linux 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Shell: GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)
(it's WSL under Windows)

 

 

### Anything else?

It seems that the function _sops_dec_get_type (around here: https://github.com/jkroepke/helm-secrets/blob/main/scripts/backends/sops.sh#L87)  greps for a single line consisting of "sops:"

```bash
if grep -Fxq 'sops:' "${1}"; then
        echo 'yaml'
```
Now if the line is broken up from LF to LF then it won't match if the line-endings are CR LF.

The helm-secrets < 4.0.0 were hardcoded to 'yaml'.

**Comment by jkroepke** [comment]
Can you provide a grep that works on any line ending=

**Comment by PoliM** [comment]
I'm currently looking at how the tests are implemented. And I think we have to be careful how to push test-data because of the automatic conversion that can happen. But I have an idea using .gitattributes. And yes, I'll try to find a grep that works.

**Comment by jkroepke** [comment]
To avoid auto conversion, use the .gitattributes

https://github.com/jkroepke/helm-secrets/blob/9af00a09a38c222ec3390ea2480da00a8deca4eb/.gitattributes#L3
