### ISSUE TITLE
Detection of file encryption for SOPS backend is very slow on large files

### ISSUE THREAD

**Issue by PoliM** [jkroepke/helm-secrets#292]
### Current Behavior

We have a large YAML file (about 500 KB) that is encrypted using SOPS. There is a point in the decrypt script where it asks the backend whether that file is encrypted. That function takes a long time (about 5-15 minutes) to detect that it is encrypted:

https://github.com/jkroepke/helm-secrets/blob/0a6e9a41fd4b91debdfb514375fceb0e56229046/scripts/backends/sops.sh#L11-L19

The 3.15.0 version just grepped over it and was quick: 

https://github.com/jkroepke/helm-secrets/blob/ea184cce75475b7e0434a37ee0053aa338d38751/scripts/drivers/sops.sh#L11-L15

Technically it is not a bug, but the long time leads to timeouts during "helmfile template" (which could be circumvented by extending the timeout, of course). But I still think it would be a good idea to improve that. I'm not a shell script guru, that's why I'm not sure about the change that was made in the detection.

### Expected Behavior

Stay bellow 10 s for a 500 KB SOPS YAML file.

### Steps To Reproduce

```markdown
1. Create a large YAML file. For example:
´´´bash
echo "data: |" > large.yaml
while IFS= read -r line; do
   echo "  $line" >> large.yaml
done < <(curl https://loripsum.net/api/300/verylong/plaintext)
´´´

2. encrypt it using SOPS
3. helm secrets decrypt large-encrypted.yaml
```

### Environment

- Helm Version: 3.10.2
- Helm Secrets Version: 4.2.1
- OS: Linux 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Shell: GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)
    (it's WSL under Windows)

**Comment by jkroepke** [comment]
Good to know. I thought shell builtins are prefferable. I will revert it.0

**Comment by PoliM** [comment]
Thanks for the fix, and sorry I didn't see the message earlier. But I tried your patch on our system and it worked. (y)
