### ISSUE TITLE
helm wrapper doesn't process args of the form `--value=my_sops_file.yaml`

### ISSUE THREAD

**Issue by tyrken** [jkroepke/helm-secrets#32]
Just hit a minor issue with this otherwise very useful fork (not sure if fork specific) - it doesn't spot the alternative form of specifying `--values` arguments where you use an equals sign between option and optarg.  I.e. the first line works:

`helm secrets template myrelease myrepo/mychart --values my_sops_file.yaml`
`helm secrets template myrelease myrepo/mychart --values=my_sops_file.yaml`

... whereas the second invisibly skips decryption (i.e. inserts ciphertext values instead of plaintext).  Hopefully you can extend the arg processing in helm.sh...

**Comment by jkroepke** [comment]
Thanks for the hint!

**Comment by tyrken** [comment]
Thanks - working now!
