### ISSUE TITLE
example execution fails

### ISSUE THREAD

**Issue by j-beaver** [jkroepke/helm-secrets#320]
### Current Behavior

I've got an error executing first decryption example

$ gpg --import tests/assets/gpg/private.gpg
gpg: key B430C4E58E2BBBA3: public key "jkroepke/helm-secrets DEMO (DONT USE THIS KEY IN PRODUCTION) <github@jkroepke.de>" imported
gpg: key B430C4E58E2BBBA3: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1

$ helm secrets decrypt examples/sops/secrets.yaml
error loading config: no matching creation rules found
[helm-secrets] Error while decrypting file: examples/sops/secrets.yaml
[helm-secrets] File is not encrypted: examples/sops/secrets.yaml
Error: plugin "secrets" exited with error

### Expected Behavior

proper file decryption

### Steps To Reproduce

```markdown
git clone git@github.com:jkroepke/helm-secrets.git
cd helm-secrets
gpg --import tests/assets/gpg/private.gpg
helm secrets decrypt examples/sops/secrets.yaml
```

### Environment

- Helm Version: 3.9.4
- Helm Secrets Version:  4.2.0
- ArgoCD Version
- OS: Linux
- Shell: bash

**Comment by jkroepke** [comment]
Works on my machine

```
jkr@joe-nb helm-secrets % gpg --import tests/assets/gpg/private.gpg

gpg: key B430C4E58E2BBBA3: "jkroepke/helm-secrets DEMO (DONT USE THIS KEY IN PRODUCTION) <github@jkroepke.de>" not changed
gpg: key B430C4E58E2BBBA3: secret key imported
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg:       secret keys read: 1
gpg:  secret keys unchanged: 1
jkr@joe-nb helm-secrets % helm secrets decrypt examples/sops/secrets.yaml

podAnnotations:
    secret: value%    
```
