### ISSUE TITLE
Dockerfile to use helm secrets via docker container

### ISSUE THREAD

**Issue by sutux** [jkroepke/helm-secrets#324]
### Problem Statement

Hi,

I need a docker image to test my helm charts with helm secrets in my CI pipeline to do something equal to

`
docker run -ti --rm -v $(pwd):/apps -v ~/private.key:/tmp/private.key -w /apps helm-secrets sh -c "gpg --import /tmp/private.key ; helm secrets template -f secrets.yaml . --output-dir manifests"
`

or

`
docker run -ti --rm -v $(pwd):/apps -v ~/private.key:/tmp/private.key -w /apps helm-secrets sh -c "helm template -f 'secrets+gpg-import:///tmp/private.key?secrets.yaml' . --output-dir manifests"
`
I haven't found any documentation to use helm secrets as docker. So I thought this feature is missing.

There is a Dockerfile in this project that could do this but something is missing and I'm not sure if this is intentional or not.

For docker-compose there is probably the same issue but I haven't tried it.

### Proposed Solution

I made some changes to the Dockerfile to work for me:

```
diff --git a/Dockerfile b/Dockerfile
index cea9bd3..f1b8cbc 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,9 +3,11 @@ FROM alpine:latest
 ENV PATH="$PATH:/opt/custom-tools/" \
     SOPS_VERSION=3.7.2 \
     HELM_VERSION=3.8.2 \
-    KUBECTL_VERSION=1.23.5
+    KUBECTL_VERSION=1.23.5 \
+    USER="appuser"
 
 RUN apk add --no-cache gnupg
+RUN adduser -D $USER
 
 SHELL ["/bin/sh", "-exc"]
 
@@ -21,5 +23,7 @@ RUN if [ "$(uname -m)" == "x86_64" ]; then CURL_ARCH=amd64; GO_ARCH=amd64; else
     && chmod +x /opt/custom-tools/* /usr/local/bin/helm \
     && /opt/custom-tools/curl --version && /opt/custom-tools/sops --version && /opt/custom-tools/kubectl version --client --short && /usr/local/bin/helm version --short
 
-USER 1001
+USER $USER
+
+RUN helm plugin install .
```

### Environment

- Helm Version: 3.8.2
- Helm Secrets Version: 26ef7be435037bfa6a14fec10c791a80919070be
- OS: Ubuntu 22.04
- Shell: bash

### Acceptance Criteria

- [ ] As a user, I can build a helm secrets docker image out of the repository.
- [ ] As a user, I can use the [usage examples](https://github.com/jkroepke/helm-secrets/wiki/Usage#usage-examples) via docker container
- [ ] As a user, I can use the helm wrapper via docker container.
- [ ] As a user, I can use helm secrets with the downloader plugin via docker container.
- [ ] The new feature is appropriately documented.

**Comment by jkroepke** [comment]
With `HELM_PLUGINS=/opt/custom-tools/` as env, it should work at least.

I could not remember, why there is a Dockerfile. Maybe I need one for run linux tests on my mac.

**Comment by sutux** [comment]
Ok, this works but I also have to add the user. The line `USER 1001` has some side effects because there is no user with this ID.
For example, I cannot use `gpg --import`.

```
$ docker run -ti --rm -v $(pwd):/apps -v ~/private.key:/tmp/private.key -w /apps helm-secrets sh -c "gpg --import /tmp/private.key"
gpg: Fatal: can't create directory '//.gnupg': Permission denied
```

I would like to add the Variable `HELM_PLUGINS=/opt/custom-tools/` to the Dockerfile.
I would also use an unique UID (>10000) as the same UID should not be present on the host system.
Something like:

```
diff --git a/Dockerfile b/Dockerfile
index cea9bd3..be9b2c0 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,11 +1,15 @@
 FROM alpine:latest
 
 ENV PATH="$PATH:/opt/custom-tools/" \
+    HELM_PLUGINS="/opt/custom-tools/" \
     SOPS_VERSION=3.7.2 \
     HELM_VERSION=3.8.2 \
     KUBECTL_VERSION=1.23.5
 
 RUN apk add --no-cache gnupg
+RUN addgroup -g 10001 appuser \
+    && adduser -D -u 10001 -G appuser appuser
 
 SHELL ["/bin/sh", "-exc"]
 
@@ -21,5 +25,5 @@ RUN if [ "$(uname -m)" == "x86_64" ]; then CURL_ARCH=amd64; GO_ARCH=amd64; else
     && chmod +x /opt/custom-tools/* /usr/local/bin/helm \
     && /opt/custom-tools/curl --version && /opt/custom-tools/sops --version && /opt/custom-tools/kubectl version --client --short && /usr/local/bin/helm version --short
 
-USER 1001
+USER appuser
```

I tried the following command and it works perfect:

`docker run -u $(id -u) -ti --rm -v $(pwd):/apps -v ~/private.key:/tmp/private.key -w /apps helm-secrets sh -c "helm template -f 'secrets+gpg-import:///tmp/private.key?secrets.yaml' . --output-dir manifests"`

**Comment by jkroepke** [comment]
Is this fine? Then I would merge this
https://github.com/jkroepke/helm-secrets/blob/b12bde5843c29219ca145635ba38d69929c89983/Dockerfile

You could easily build the docker image locally by running 

Since I may not plan to distribute a official image

```
docker build -t helm-secrets https://github.com/jkroepke/helm-secrets.git#main
```

May helps you.

**Comment by sutux** [comment]
It works well with your changes. Thank you!
