### ISSUE TITLE
Protocol sniffing broken for local paths with "http" prefix

### ISSUE THREAD

**Issue by abursavich** [jkroepke/helm-secrets#328]
### Current Behavior

```
➜ helm secrets template -f httpbin/values.yaml ...
curl: (6) Could not resolve host: httpbin
[helm-secrets] Unable to download url httpbin/dev/values.yaml
[helm-secrets] File does not exist: httpbin/dev/values.yaml
Error: plugin "secrets" exited with error
```

### Expected Behavior

Local file names prefixed with "http" should be treated as local files instead of remote http files.

### Environment

- Helm Version: v3.10.3
- Helm Secrets Version: 3.14.0
- ArgoCD Version: N/A
- OS:  Darwin 21.5.0
- Shell: zsh

### Anything else?

The aggressive pattern is `http*`: https://github.com/jkroepke/helm-secrets/blob/v4.2.2/scripts/lib/file.sh#L20

It should probably be `http://*|https://*` or something similar.

**Comment by jkroepke** [comment]
thats funny, nice catch.
