### ISSUE TITLE
Not able to use secret://https://<gitlab repo> with ArgoCD Applications

### ISSUE THREAD

**Issue by revaspeho** [jkroepke/helm-secrets#332]
### Current Behavior

Hello, I am trying to use the helm secret plugin with my ARGO CD. I have two private gitlab repos. REPO A has the helm chart and REPO B has a SOPS encrypted values.yaml file. When deploying my HELM Chart on ARGO CD, I am trying to specify REPO B encrypted file as a helm value. When I use secrets://https://<url> ARGO CD, I get the error:

`rpc error: code = Unknown desc = Manifest generation error (cached): helm template`

 I have tested the <url> in an incognito window and have confirmed that it returns the raw yaml. I have tested https:// protocol alone and ARGO CD handles this (injecting the helm values encrypted as expected). I also created a third repo (REPO C) that had the helm chart and the encrypted values.yaml file together to test just secrets://<filepath> alone and that worked correctly. Therefore, it seems that ArgoCD does not like both secrets://https:// together. Any thoughts?

### Environment

- Helm Version: 3.8.1
- Helm Secrets Version: 3.15.0
- ArgoCD Version: 2.4.12
- OS:
- Shell:

**Comment by jkroepke** [comment]
There should be an additional error after that. Maybe restart redis to clear cache

**Comment by jkroepke** [comment]
feels strange here, in the picture, you are using secrets:/https:/code instead `secrets:/https:/code`

**Comment by revaspeho** [comment]
Ah gotcha, I changed the manifest configurations to be secrets://https://code and am still getting the same error. Here is the error + yaml file:

![Screen Shot 2023-01-30 at 10 12 06 PM](https://user-images.githubusercontent.com/83427905/215681390-8b5e99ec-cc3e-4b64-b5a0-1682b951d3c2.png)


![Screen Shot 2023-01-30 at 10 12 24 PM](https://user-images.githubusercontent.com/83427905/215681423-a86bc694-709f-490d-a7d9-38de3857bca0.png)

**Comment by jkroepke** [comment]
hm, is this correct? `{REGSCALE_TOKEN}` vs. `${REGSCALE_TOKEN}`. Did you ever try `$REGSCALE_TOKEN` ?

**Comment by revaspeho** [comment]
Hi @jkroepke I have tried it with those different environmental variable variations. For testing purposes, I have hardcoded my regscale token into the url, but have gotten same error. I am adding the screenshot with the environmental variable to not expose the token. Additionally, I have exec into my argocd-repo-server pod and have confirmed that curl is installed.

e.g. curl "https://code.batcave.internal.cms.gov/api/v4/projects/248/repository/files/dev-bta-main%2Fregscale-values-secret.enc.yaml/raw?ref=BO-2484-2&private_token=$REGSCALE_TOKEN" works correctly

However when I do helm secrets view https://code.batcave.internal.cms.gov/api/v4/projects/248/repository/files/dev-bta-main%2Fregscale-values-secret.enc.yaml/raw?ref=BO-2484-2&private_token=$REGSCALE_TOKEN I get the error:
`Unable to detect 'curl' or 'wget'.
[helm-secrets] Unable to download url https://code.batcave.internal.cms.gov/api/v4/projects/248/repository/files/dev-bta-main%2Fregscale-values-secret.enc.yaml/raw?ref=BO-2484-2
Error: plugin "secrets" exited with error`

This is the rest of the ArgoCD error:
![Screen Shot 2023-01-31 at 12 16 40 PM](https://user-images.githubusercontent.com/83427905/215873879-ccf0def4-c1d0-4631-898b-bff5fc1dd413.png)

**Comment by jkroepke** [comment]
is HELM_SECRETS_CURL_PATH defined, but with an wrong path?

**Comment by revaspeho** [comment]
Hi @jkroepke ah I changed the curl path (I guess my argo-server-repo already had curl located in /usr/bin/curl so the initcontainer was not downloading it to /custom-tools/curl. I am getting a new error: failed exit status `2: error loading config: no matching creation rules found panic: runtime error: invalid memory address.` I find this strange since I can execute `helm secrets view "https://code.batcave.internal.cms.gov/api/v4/projects/248/repository/files/dev-bta-main%2Fregscale-values-secret.enc.yaml/raw?ref=BO-2484-2&private_token=$REGSCALE_TOKEN"
` in the repo server and it successfully decodes the secrets. I am using AWS IRSA. Here is the issue:
<img width="753" alt="Screen Shot 2023-01-31 at 4 09 07 PM" src="https://user-images.githubusercontent.com/83427905/215913346-3fc75eca-abd3-48f5-8fc1-d34e550f27cb.png">

**Comment by jkroepke** [comment]
Does helm secrets template works, if you run it locally? The panic should come from helm and fixed in 3.9.0 or later.

**Comment by revaspeho** [comment]
Hi @jkroepke which command should I be running? Is it helm template -f secrets://https://<code>? Also the error is saying config: no matching creation rules found. Is this due to helm secrets not knowing what kms sops key to use?

**Comment by jkroepke** [comment]
`helm template -f secrets://https://` is correct.

> Is this due to helm secrets not knowing what kms sops key to use?

Normally, the information is stored inside the sops encrypted file as metadata.

Is there a diff between `helm template -f secrets://https://` and `helm secrets -f https://`?

**Comment by revaspeho** [comment]
Hey @jkroepke yes my sops encrypted file has the sops metadata. I guess the question is how does ArgoCD know which key to use for decryption if the file is a url instead of not being in the source repository? Is helm secrets expecting that whatever path I set in source.path, a sops.yaml file should be there?

**Comment by jkroepke** [comment]
helm-secrets is calling sops in background. since the key is stored in the metadata, sops known which keys is needed for decryption. The location does not matter. I assume, you are using something like AWS KMS? oder gpg?

Did you test the env `HELM_SECRETS_BACKEND_ARGS="--config /dev/null"` ?

**Comment by revaspeho** [comment]
Hi @jkroepke yes I am using an AWS KMS. I added the env variable but no luck. I noticed when I ran helm secrets -f https://code.batcave.internal.cms.gov/api/v4/projects/267/repository/files/regscale-values-secret.enc.yaml/raw?ref=main,  I am getting this error: 
`unknown shorthand flag: 'f' in -f`. 

When I use helm secrets -f https://user:password@raw.githubusercontent.com/jkroepke/helm-secrets/main/examples/sops/secrets.yaml

I get this error:
`Group 0: FAILED
  D6174A02027050E59C711075B430C4E58E2BBBA3: FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: Could not
      | load secring: open /home/argocd/.gnupg/secring.gpg: no such
      | file or directory; GPG binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.`

which is what I would expect. If I do `helm secrets view <code>`, it works as expected. I wonder if there is an issue with helm secrets -f ?

**Comment by jkroepke** [comment]
Yeah, helm secrets -f is not valid. Only helm secrets [ helm command ] -f, like helm secrets template. Sorry it was a bit late.

**Comment by revaspeho** [comment]
Hmm understood, well getting back to setting the ArgoCD error, are there any other fixes I should look at to resolve this issue?

**Comment by jkroepke** [comment]
Could you upgrade the helm-secret version to the lasted one? Maybe https://github.com/jkroepke/helm-secrets/pull/315 is the issue here. (and this is not released yet.. whoops)

**Comment by FrankelJb** [comment]
Perhaps related, perhaps not.

I'm trying to use multiple sops encrypted value files in an application. One is remotely stored on a local gitea server that is publicly accessible and the other is stored locally in the chart. My application looks something like what's below. The local url is accessible from within the cluster, I've curled the file. I've built the application using `helm template` and the secret gets decrypted and the output has the fields updated correctly.

When I run this in `argocd`, there is no error and the fields aren't updated. I'm a bit stuck on where to even look. Could this be caused by something `helm secrets` related?

```
project: default
source:
  repoURL: 'https://gitea.local/gitea_admin/cluster.git'
  path: selfhosted/apps/libreddit
  targetRevision: main
  helm:
    valueFiles:
      - >-
        secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml
      - >-
        secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?https://gitea.local/gitea_admin/secrets/raw/branch/main/helm-secrets.yaml
```

**Comment by mrnim94** [comment]
It doesn't work with GitLab, bitbucket.
```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://helmcharts.opsmx.com/
    targetRevision: "2.2.4"
    chart: spinnaker
    helm:
      valueFiles:
        # if AWS KMS or GCP is used
        - secrets://https://gitlab.nimtechnology.com/nim/manifest-k8s/-/raw/master/spinnaker/values_helm_encrypted.yaml```
This is an issue that I collect on Argocd

```
rpc error: code = Unknown desc = `helm template . --name-template app --namespace default --kube-version 1.25 --values secrets://https://gitlab.nimtechnology.com/nim/manifest-k8s/-/raw/master/spinnaker/values_helm_encrypted.yaml --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions argoproj.io/v1alpha1/ClusterWorkflowTemplate --api-versions argoproj.io/v1alpha1/CronWorkflow --api-versions argoproj.io/v1alpha1/Workflow --api-versions argoproj.io/v1alpha1/WorkflowArtifactGCTask --api-versions argoproj.io/v1alpha1/WorkflowEventBinding --api-versions argoproj.io/v1alpha1/WorkflowTaskResult --api-versions argoproj.io/v1alpha1/WorkflowTaskSet --api-versions argoproj.io/v1alpha1/WorkflowTemplate --api-versions autopilot.k0sproject.io/v1beta2 --api-versions autopilot.k0sproject.io/v1beta2/ControlNode --api-versions autopilot.k0sproject.io/v1beta2/Plan --api-versions autopilot.k0sproject.io/v1beta2/UpdateConfig --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions catalog.cattle.io/v1 --api-versions catalog.cattle.io/v1/App --api-versions catalog.cattle.io/v1/ClusterRepo --api-versions catalog.cattle.io/v1/Operation --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions cilium.io/v2 --api-versions cilium.io/v2/CiliumClusterwideNetworkPolicy --api-versions cilium.io/v2/CiliumEndpoint --api-versions cilium.io/v2/CiliumExternalWorkload --api-versions cilium.io/v2/CiliumIdentity --api-versions cilium.io/v2/CiliumNetworkPolicy --api-versions cilium.io/v2/CiliumNode --api-versions cilium.io/v2alpha1 --api-versions cilium.io/v2alpha1/CiliumLoadBalancerIPPool --api-versions cilium.io/v2alpha1/CiliumNodeConfig --api-versions cluster.x-k8s.io/v1alpha3 --api-versions cluster.x-k8s.io/v1alpha3/Cluster --api-versions cluster.x-k8s.io/v1alpha3/Machine --api-versions cluster.x-k8s.io/v1alpha3/MachineDeployment --api-versions cluster.x-k8s.io/v1alpha3/MachineHealthCheck --api-versions cluster.x-k8s.io/v1alpha3/MachineSet --api-versions cluster.x-k8s.io/v1alpha4 --api-versions cluster.x-k8s.io/v1alpha4/Cluster --api-versions cluster.x-k8s.io/v1alpha4/Machine --api-versions cluster.x-k8s.io/v1alpha4/MachineDeployment --api-versions cluster.x-k8s.io/v1alpha4/MachineHealthCheck --api-versions cluster.x-k8s.io/v1alpha4/MachineSet --api-versions cluster.x-k8s.io/v1beta1 --api-versions cluster.x-k8s.io/v1beta1/Cluster --api-versions cluster.x-k8s.io/v1beta1/Machine --api-versions cluster.x-k8s.io/v1beta1/MachineDeployment --api-versions cluster.x-k8s.io/v1beta1/MachineHealthCheck --api-versions cluster.x-k8s.io/v1beta1/MachineSet --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions fleet.cattle.io/v1alpha1 --api-versions fleet.cattle.io/v1alpha1/Bundle --api-versions fleet.cattle.io/v1alpha1/BundleDeployment --api-versions fleet.cattle.io/v1alpha1/BundleNamespaceMapping --api-versions fleet.cattle.io/v1alpha1/Cluster --api-versions fleet.cattle.io/v1alpha1/ClusterGroup --api-versions fleet.cattle.io/v1alpha1/ClusterRegistration --api-versions fleet.cattle.io/v1alpha1/ClusterRegistrationToken --api-versions fleet.cattle.io/v1alpha1/Content --api-versions fleet.cattle.io/v1alpha1/GitRepo --api-versions fleet.cattle.io/v1alpha1/GitRepoRestriction --api-versions fleet.cattle.io/v1alpha1/ImageScan --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions flowcontrol.apiserver.k8s.io/v1beta2 --api-versions flowcontrol.apiserver.k8s.io/v1beta2/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta2/PriorityLevelConfiguration --api-versions gitjob.cattle.io/v1 --api-versions gitjob.cattle.io/v1/GitJob --api-versions helm.k0sproject.io/v1beta1 --api-versions helm.k0sproject.io/v1beta1/Chart --api-versions longhorn.io/v1beta1 --api-versions longhorn.io/v1beta1/BackingImage --api-versions longhorn.io/v1beta1/BackingImageDataSource --api-versions longhorn.io/v1beta1/BackingImageManager --api-versions longhorn.io/v1beta1/Backup --api-versions longhorn.io/v1beta1/BackupTarget --api-versions longhorn.io/v1beta1/BackupVolume --api-versions longhorn.io/v1beta1/Engine --api-versions longhorn.io/v1beta1/EngineImage --api-versions longhorn.io/v1beta1/InstanceManager --api-versions longhorn.io/v1beta1/Node --api-versions longhorn.io/v1beta1/RecurringJob --api-versions longhorn.io/v1beta1/Replica --api-versions longhorn.io/v1beta1/Setting --api-versions longhorn.io/v1beta1/ShareManager --api-versions longhorn.io/v1beta1/Volume --api-versions longhorn.io/v1beta2 --api-versions longhorn.io/v1beta2/BackingImage --api-versions longhorn.io/v1beta2/BackingImageDataSource --api-versions longhorn.io/v1beta2/BackingImageManager --api-versions longhorn.io/v1beta2/Backup --api-versions longhorn.io/v1beta2/BackupTarget --api-versions longhorn.io/v1beta2/BackupVolume --api-versions longhorn.io/v1beta2/Engine --api-versions longhorn.io/v1beta2/EngineImage --api-versions longhorn.io/v1beta2/InstanceManager --api-versions longhorn.io/v1beta2/Node --api-versions longhorn.io/v1beta2/Orphan --api-versions longhorn.io/v1beta2/RecurringJob --api-versions longhorn.io/v1beta2/Replica --api-versions longhorn.io/v1beta2/Setting --api-versions longhorn.io/v1beta2/ShareManager --api-versions longhorn.io/v1beta2/Snapshot --api-versions longhorn.io/v1beta2/SupportBundle --api-versions longhorn.io/v1beta2/SystemBackup --api-versions longhorn.io/v1beta2/SystemRestore --api-versions longhorn.io/v1beta2/Volume --api-versions management.cattle.io/v3 --api-versions management.cattle.io/v3/APIService --api-versions management.cattle.io/v3/AuthConfig --api-versions management.cattle.io/v3/Catalog --api-versions management.cattle.io/v3/CatalogTemplate --api-versions management.cattle.io/v3/CatalogTemplateVersion --api-versions management.cattle.io/v3/Cluster --api-versions management.cattle.io/v3/ClusterAlert --api-versions management.cattle.io/v3/ClusterAlertGroup --api-versions management.cattle.io/v3/ClusterAlertRule --api-versions management.cattle.io/v3/ClusterCatalog --api-versions management.cattle.io/v3/ClusterMonitorGraph --api-versions management.cattle.io/v3/ClusterRegistrationToken --api-versions management.cattle.io/v3/ClusterRoleTemplateBinding --api-versions management.cattle.io/v3/ClusterTemplate --api-versions management.cattle.io/v3/ClusterTemplateRevision --api-versions management.cattle.io/v3/ComposeConfig --api-versions management.cattle.io/v3/DynamicSchema --api-versions management.cattle.io/v3/EtcdBackup --api-versions management.cattle.io/v3/Feature --api-versions management.cattle.io/v3/FleetWorkspace --api-versions management.cattle.io/v3/GlobalDns --api-versions management.cattle.io/v3/GlobalDnsProvider --api-versions management.cattle.io/v3/GlobalRole --api-versions management.cattle.io/v3/GlobalRoleBinding --api-versions management.cattle.io/v3/Group --api-versions management.cattle.io/v3/GroupMember --api-versions management.cattle.io/v3/KontainerDriver --api-versions management.cattle.io/v3/ManagedChart --api-versions management.cattle.io/v3/MonitorMetric --api-versions management.cattle.io/v3/MultiClusterApp --api-versions management.cattle.io/v3/MultiClusterAppRevision --api-versions management.cattle.io/v3/Node --api-versions management.cattle.io/v3/NodeDriver --api-versions management.cattle.io/v3/NodePool --api-versions management.cattle.io/v3/NodeTemplate --api-versions management.cattle.io/v3/Notifier --api-versions management.cattle.io/v3/PodSecurityAdmissionConfigurationTemplate --api-versions management.cattle.io/v3/PodSecurityPolicyTemplate --api-versions management.cattle.io/v3/PodSecurityPolicyTemplateProjectBinding --api-versions management.cattle.io/v3/Preference --api-versions management.cattle.io/v3/Project --api-versions management.cattle.io/v3/ProjectAlert --api-versions management.cattle.io/v3/ProjectAlertGroup --api-versions management.cattle.io/v3/ProjectAlertRule --api-versions management.cattle.io/v3/ProjectCatalog --api-versions management.cattle.io/v3/ProjectMonitorGraph --api-versions management.cattle.io/v3/ProjectNetworkPolicy --api-versions management.cattle.io/v3/ProjectRoleTemplateBinding --api-versions management.cattle.io/v3/RancherUserNotification --api-versions management.cattle.io/v3/RkeAddon --api-versions management.cattle.io/v3/RkeK8sServiceOption --api-versions management.cattle.io/v3/RkeK8sSystemImage --api-versions management.cattle.io/v3/RoleTemplate --api-versions management.cattle.io/v3/SamlToken --api-versions management.cattle.io/v3/Setting --api-versions management.cattle.io/v3/Template --api-versions management.cattle.io/v3/TemplateContent --api-versions management.cattle.io/v3/TemplateVersion --api-versions management.cattle.io/v3/Token --api-versions management.cattle.io/v3/User --api-versions management.cattle.io/v3/UserAttribute --api-versions metallb.io/v1alpha1 --api-versions metallb.io/v1alpha1/AddressPool --api-versions metallb.io/v1beta1 --api-versions metallb.io/v1beta1/AddressPool --api-versions metallb.io/v1beta1/BFDProfile --api-versions metallb.io/v1beta1/BGPAdvertisement --api-versions metallb.io/v1beta1/BGPPeer --api-versions metallb.io/v1beta1/Community --api-versions metallb.io/v1beta1/IPAddressPool --api-versions metallb.io/v1beta1/L2Advertisement --api-versions metallb.io/v1beta2 --api-versions metallb.io/v1beta2/BGPPeer --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/Alertmanager --api-versions monitoring.coreos.com/v1/Prometheus --api-versions monitoring.coreos.com/v1/PrometheusRule --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions project.cattle.io/v3 --api-versions project.cattle.io/v3/App --api-versions project.cattle.io/v3/AppRevision --api-versions provisioning.cattle.io/v1 --api-versions provisioning.cattle.io/v1/Cluster --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions rke-machine-config.cattle.io/v1 --api-versions rke-machine-config.cattle.io/v1/Amazonec2Config --api-versions rke-machine-config.cattle.io/v1/AzureConfig --api-versions rke-machine-config.cattle.io/v1/DigitaloceanConfig --api-versions rke-machine-config.cattle.io/v1/HarvesterConfig --api-versions rke-machine-config.cattle.io/v1/LinodeConfig --api-versions rke-machine-config.cattle.io/v1/VmwarevsphereConfig --api-versions rke-machine.cattle.io/v1 --api-versions rke-machine.cattle.io/v1/Amazonec2Machine --api-versions rke-machine.cattle.io/v1/Amazonec2MachineTemplate --api-versions rke-machine.cattle.io/v1/AzureMachine --api-versions rke-machine.cattle.io/v1/AzureMachineTemplate --api-versions rke-machine.cattle.io/v1/DigitaloceanMachine --api-versions rke-machine.cattle.io/v1/DigitaloceanMachineTemplate --api-versions rke-machine.cattle.io/v1/HarvesterMachine --api-versions rke-machine.cattle.io/v1/HarvesterMachineTemplate --api-versions rke-machine.cattle.io/v1/LinodeMachine --api-versions rke-machine.cattle.io/v1/LinodeMachineTemplate --api-versions rke-machine.cattle.io/v1/VmwarevsphereMachine --api-versions rke-machine.cattle.io/v1/VmwarevsphereMachineTemplate --api-versions rke.cattle.io/v1 --api-versions rke.cattle.io/v1/CustomMachine --api-versions rke.cattle.io/v1/ETCDSnapshot --api-versions rke.cattle.io/v1/RKEBootstrap --api-versions rke.cattle.io/v1/RKEBootstrapTemplate --api-versions rke.cattle.io/v1/RKECluster --api-versions rke.cattle.io/v1/RKEControlPlane --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/CSIStorageCapacity --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions ui.cattle.io/v1 --api-versions ui.cattle.io/v1/NavLink --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --include-crds` failed exit status 1: Error: YAML parse error on helm-values-getter/templates/values.yaml: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context Use --debug flag to render out invalid YAML [helm-secrets] File does not exist: secrets://https://gitlab.nimtechnology.com/nim/manifest-k8s/-/raw/master/spinnaker/values_helm_encrypted.yaml Error: plugin "secrets" exited with error
```

**Comment by mrnim94** [comment]
> I cant see any auth on the url here Is your repository publc?

I use GitLab self-host. This is a private repository.

**Comment by jkroepke** [comment]
And where you do the authentication?

**Comment by mrnim94** [comment]
> And where you do the authentication?

I config authentication at Settings > repository
![image](https://user-images.githubusercontent.com/50592567/224121691-9ed77d7f-d4bb-44bc-9550-98df912d4144.png)

Is this way or right?

**Comment by jkroepke** [comment]
helm-secrets cant use the credentials from argocd, since ArgoCD does not expose them...

A pre-authenticated URL is required, e.g. 'https://git.local/user1/myrepo/raw/master/myfile.txt?private_token=ahgiretherghaeoi' (The URL must work in a private browser session, without sign in into Gitlab Instance)

**Comment by mrnim94** [comment]
> helm-secrets cant use the credentials from argocd, since ArgoCD does not expose them...
> 
> A pre-authenticated URL is required, e.g. 'https://git.local/user1/myrepo/raw/master/myfile.txt?private_token=ahgiretherghaeoi' (The URL must work in a private browser session, without sign in into Gitlab Instance)

I looked into the pre-authenticated URL on GitLab. But It hasn't been supported.

**Comment by Vormillion** [comment]
> rivate brows

Did you solve it?
