### ISSUE TITLE
Exclamation mark in --set argument leads to backend not found error

### ISSUE THREAD

**Issue by dschuldt** [jkroepke/helm-secrets#352]
### Current Behavior

When exclamation marks are used within --set arguments, the helm secrets process throws an error that the secret backend cannot be found.

### Expected Behavior

The value in the --set argument should not be interpreted as a secret backend

### Steps To Reproduce

```markdown
Consider this helm install command:


helm secrets upgrade --install --dry-run myrelease ./helm \
  -f ./helm/values.yaml \
  -f ./helm/secrets.yaml \
  --set mykey='my!value'
```

This leads to the following error

_[helm-secrets] Decrypt: ./helm/secrets.yaml
[helm-secrets] Can't find secret backend: my_
```


### Environment

- Helm Version: v3.11.1
- Helm Secrets Version: 4.4.0
- OS: Linux/MacOS
- Shell: ZSH


### Anything else?

_No response_

**Comment by jkroepke** [comment]
Hm, it feels like a stupid behavior from helm-secrets
