### ISSUE TITLE
ArgoCD and Helm secrets v3.15.0, wrapper/helm.sh doesn't exist

### ISSUE THREAD

**Issue by dignajar** [jkroepke/helm-secrets#359]
### Current Behavior

Following the documentation from here https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#multi-source-application-support-beta using Helm secrets v3.15.0, I noticed the file `wrapper/helm.sh` doesn't exist.

The following line is failing because the file doesn't exist.
```
cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm
```

Inside the argocd-server container, I can see the following files in the directory `/custom-tools/helm-plugins/helm-secrets/scripts/wrapper`
```
 |-wrapper
 | |-run.cmd
 | |-sh.cmd
```

### Environment

- Helm Version: 3.10.3
- Helm Secrets Version: 3.15.0
- ArgoCD Version: 2.6.1

**Comment by dignajar** [comment]
I replaced this line:
```
cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm
```

for this line
```
printf '#!/usr/bin/env sh\nexec %s secrets "$@"' "${HELM_SECRETS_HELM_PATH}" > "/custom-tools/helm"
```

**Comment by jkroepke** [comment]
Its expected, and documented. The Multi Source Application feature requires helm secrets 4.4.0

> Multi-source applications requires at least helm-secrets [4.4.0](https://github.com/jkroepke/helm-secrets/releases/tag/v4.4.0) and some special [instructions](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#multi-source-application-support-beta)!
