### ISSUE TITLE
Multisource combine

### ISSUE THREAD

**Issue by newbenji** [jkroepke/helm-secrets#363]
### Problem Statement

Will you get the plugin to work when the new argocd comes out with this

https://github.com/argoproj/argo-cd/commit/b11a959b68e15fd58082bc2ec3c83f30edebdd79

So its possible to use sops with sources ?
Cant get it to work with your beta as it is now

### Environment

- Helm Version:
- Helm Secrets Version:
- OS:
- Shell:

**Comment by jkroepke** [comment]
It should work out of the, depends on the implementation on detail. but yeah...

https://github.com/argoproj/argo-cd/issues/11866#issuecomment-1522250391

We will see once its merged.

**Comment by jkroepke** [comment]
There is a confirmation that it work with that PR.

https://github.com/argoproj/argo-cd/pull/12508#issuecomment-1527718678
