### ISSUE TITLE
Azure keyvault cloud integration is not working

### ISSUE THREAD

**Issue by manojm7181** [jkroepke/helm-secrets#364]
### Current Behavior

We are trying to fetch secrets from azure keyvault and getting below error when we executed below command 

           helm secrets template -f values.yaml templates/chart/secret.yaml

            [helm-secrets] Decrypt skipped: values.yaml
            Error: file 'secret.yaml' seems to be a YAML file, but expected a gzipped archive
            Error: plugin "secrets" exited with error

access verified by manually pulling secrets using az cli and converted file gz format and tried no luck 

### Expected Behavior

expected output of the below command is:

      helm secrets template -f values.yaml templates/chart/secret.yaml

      You should see some message form vals stating that the secrets were retrieve and the resulting content from the template in the STDOUT.

### Steps To Reproduce

```markdown
below are steps we followed : 


 1. export HELM_SECRETS_VALS_PATH=/c/tools/vals.exe
 2. HELM_SECRETS_BACKEND=vals
 3. az login
 4. prepared secrets.yaml     

        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: 'helm-secrets'   
        type: Opaque
        data:
          supersecret: '{{ .Values.azure | b64enc }}'
5. prepared values.yaml file like below


         azure: ref+azurekeyvault://my-secret-azure-key-vault/my-secret-name


6. executed below command to fetch secret 

      

          helm secrets template -f values.yaml templates/chart/secret.yaml



we are getting below error:



            [helm-secrets] Decrypt skipped: values.yaml
            Error: file 'secret.yaml' seems to be a YAML file, but expected a gzipped archive
            Error: plugin "secrets" exited with error


```

### Environment

- Helm Version: v3.11.3
- Helm Secrets Version: 4.4.2
- ArgoCD Version: v2.5.5+fc3eaec
- OS: Windows 10
- Shell: git bash
- vals: 0.25.0
-

**Comment by jkroepke** [comment]
You call helm wrong.

Correct:

```
helm secrets template -f values.yaml .
```

**Comment by raighneweng** [comment]
The documentation need updated, it may mislead users here.  https://github.com/jkroepke/helm-secrets/wiki/Cloud-Integration
```
helm secrets template -f values.yaml chart/secret.yaml
```

Also I have another question: how can combine `helm secrets` with `helm upgrade`, our current upgrading command like this:

```
helm upgrade --install server_name -f values.yaml helm_folder
```
