### ISSUE TITLE
Error: plugin "secrets" exited with error

### ISSUE THREAD

**Issue by yaroslav-svirida** [jkroepke/helm-secrets#375]
### Current Behavior

helm secrets init
GnuPG secrets encryption in Helm Charts

This plugin provides ability to encrypt/decrypt secrets files
to store in less secure places, before they are installed using
Helm.

To decrypt/encrypt/edit you need to initialize/first encrypt secrets with
sops - https://github.com/mozilla/sops

Available Commands:
  enc    	Encrypt secrets file
  dec    	Decrypt secrets file
  view   	Print secrets decrypted
  edit   	Edit secrets file and encrypt afterwards
  clean         Remove all decrypted files in specified directory (recursively)
  install	wrapper that decrypts secrets[.*].yaml files before running helm install
  template	wrapper that decrypts secrets[.*].yaml files before running helm template
  upgrade	wrapper that decrypts secrets[.*].yaml files before running helm upgrade
  lint		wrapper that decrypts secrets[.*].yaml files before running helm lint
  diff		wrapper that decrypts secrets[.*].yaml files before running helm diff
                  (diff is a helm plugin)

Error: plugin "secrets" exited with error

### Expected Behavior

Step 5: Initialize Helm Secrets
   - Before using Helm Secrets, you need to initialize it in your project. Navigate to your Helm Chart project directory and run:
     
     helm secrets init
     

   - This command initializes Helm Secrets and sets up the necessary directory structure and files.

### Steps To Reproduce

```markdown
1. minikube start
2.kubectl create namespace argocd
3.kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
4.helm plugin install https://github.com/jkroepke/helm-secrets
5. helm secrets init
```

### Environment

- Helm Version: version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"
- Helm Secrets Version: secrets	2.0.2
- ArgoCD Version: v2.6.5+60104ac
- OS: Ubuntu 22.04.2 LTS
- Shell: bash

**Comment by jkroepke** [comment]
1. there is not such comment like `helm secrets init.` where u grab this
2. helm secrets 2.0.2 is very old. If you run `helm plugin install https://github.com/jkroepke/helm-secrets`, you should get back 4.4.2

**Comment by yaroslav-svirida** [comment]
i tried to add sops in argocd+helm. I found next tutorial:
Certainly! I can provide you with a step-by-step guide on how to integrate Helm secrets into Argo CD. Before we begin, please make sure you have the following prerequisites:

1. Argo CD installed and running.
2. Helm installed.
3. Helm Secrets plugin installed (`helm-secrets`).

Now let's proceed with the integration:

Step 1: Initialize Helm Secrets
   - Run the following command to initialize Helm Secrets in your project:
     
     helm secrets init
     

Step 2: Create a Secret
   - Create a Kubernetes Secret file (`secret.yaml`) that contains the sensitive data you want to manage securely.
   - Encrypt the sensitive data using the helm secrets command:
     
     helm secrets enc secret.yaml
     

Step 3: Create a Helm Chart
   - Create a Helm Chart for your application if you don't have one already.
   - Add the encrypted secret file (`secret.yaml`) to the Helm Chart.

Step 4: Install the Helm Chart
   - Deploy the Helm Chart using Argo CD as you normally would.
   - Argo CD will apply the encrypted secret file during the deployment process.

Step 5: Decrypt the Secret
   - After the deployment, you can decrypt the secret file using the helm secrets command:
     
     helm secrets dec <path-to-secret.yaml>
     

That's it! You have successfully integrated Helm Secrets into Argo CD. The secret file is encrypted and managed securely within your Helm Chart, and Argo CD will handle the decryption and deployment process.

Remember to handle and manage your encryption keys securely to ensure the confidentiality of your secrets.

Note: The above steps assume that you have already configured Helm Secrets properly with the necessary encryption key. If you haven't set it up, please refer to the documentation of the helm-secrets plugin for instructions on how to do so.

I did like that(
Is this manual wrong?

**Comment by jkroepke** [comment]
Yeah, thats garbage.

Try this one: https://medium.com/@mprzygrodzki/argocd-with-helm-secrets-and-kms-encryption-1f0944728873

Skip the terraform part and the part with `creation_rules`
