### ISSUE TITLE
Store decryped file in temp folder

### ISSUE THREAD

**Issue by joelee2012** [jkroepke/helm-secrets#381]
### Current Behavior

when run `helm secrets upgrade/install/template` in parallel for different releases which require same secrets.yaml file ,  it will report `cannot remove 'secrets.yaml.dec': No such file or directory`, this is due to the `helm secrets` decrypt secrets in source folder and remove after it done.

### Expected Behavior

when run `helm secrets upgrade/install/template` in parallel for different releases which require same secrets.yaml file without error

### Steps To Reproduce

```markdown
run `helm secrets upgrade/install/template`  in parallel
```

### Environment

- Helm Version: v3.12.0 
- Helm Secrets Version: 4.4.2
- ArgoCD Version
- OS: wsl ubuntu 20.04 
- Shell: bash

### Anything else?

the possible solution may store the none-in-placed decrypted file in temp dir which was created at the beginning,

**Comment by jkroepke** [comment]
Hi @joelee2012 

could you do try somelike like this?
```bash
HELM_SECRETS_DEC_DIR="$(mktemp)" helm secrets upgrade/install/template
```
Alternatively, its possible to add a prefix to decrypted files:

```bash
HELM_SECRETS_DEC_PREFIX="1-" helm secrets upgrade/install/template
HELM_SECRETS_DEC_PREFIX="2-" helm secrets upgrade/install/template
```

**Comment by joelee2012** [comment]
@jkroepke thanks for sharing the context,  and how to make it works in argocd ?  
for security consideration, is it possible  to store the decrypted file in a tmp folder of user, eg.  `/home/user/.local/tmp/` ?

**Comment by joelee2012** [comment]
currently i add following code at the beginning of `wrapper/helm.sh` as workaround for argo cd
```sh
mkdir -p -m 700 /tmp/helm-secrets-tmp
HELM_SECRETS_DEC_DIR=$(mktemp -d -p /tmp/helm-secrets-tmp)
export HELM_SECRETS_DEC_DIR
```
