### ISSUE TITLE
Argocd integration doesn't work. Get error  "Failed to get the data key required to decrypt the SOPS file"

### ISSUE THREAD

**Issue by ArtemShevelyukhin** [jkroepke/helm-secrets#385]
#### Configuration

I am trying to configure sops + age + argocd

I have a simple Argocd application where defined 
```
    helm:
      valueFiles:
        - secrets+age-import://secrets.enc.yaml
```

<details>
<summary>Full example</summary>
<br>
<br>
<pre>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
  namespace: {{ $.Values.deploy.argo_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - FailOnSharedResource=true
    retry:
      limit: 0
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ $.Values.deploy.namespace }}
  project: {{ $.Values.deploy.project }}
  source:
    path: helm-secrets/helm-chart
    repoURL: <URL-TO-CHART>
    targetRevision: HEAD
    helm:
      valueFiles:
        - secrets+age-import://secrets.enc.yaml
</pre>
</details>
        
        
Also I used next options from [the doc ](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration)
- Init Container
- Mount the private key from a kubernetes secret as volume on the argocd-repo-server

<details>
<summary>Dockerfile for "Init container" option</summary>
<br>
<br>
<pre>
FROM alpine:3.18.2

ARG VERSION_HELM=3.11.0
ARG VERSION_SOPS=3.7.3

ARG VERSION_KUBECTL=0.21.0

SHELL ["/bin/sh", "-exc"]

ENV HOME=/home/user/

COPY repositories /etc/apk/
RUN apk update

RUN if [ "$(uname -m)" == "x86_64" ]; then CURL_ARCH=amd64; GO_ARCH=amd64; else CURL_ARCH="aarch64" GO_ARCH="arm64"; fi \
    && apk add --no-cache gnupg curl && adduser -D user \
    && wget -qO /usr/local/bin/sops https://github.com/mozilla/sops/releases/download/v${VERSION_SOPS}/sops-v${VERSION_SOPS}.linux.${GO_ARCH} \
    && wget -qO /usr/local/bin/kubectl https://dl.k8s.io/release/v${VERSION_KUBECTL}/bin/linux/${GO_ARCH}/kubectl \
    && wget -qO - https://get.helm.sh/helm-v${VERSION_HELM}-linux-${GO_ARCH}.tar.gz | tar xzvf - -C /usr/local/bin/ --strip-components 1 "linux-${GO_ARCH}/helm" \
    && chmod +x /usr/local/bin/*

COPY helm-secrets-v4.4.2 /home/user/.local/share/helm/plugins/helm-plugins

USER user

</pre>
</details>

<details>
<summary>Kustomize for "Init container" option</summary>
<br>
<br>
<pre>
## Patch containers
- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_PLUGINS
    value: /custom-tools/helm-plugins/

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_CURL_PATH
    value: /custom-tools/curl

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_SOPS_PATH
    value: /custom-tools/sops

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_KUBECTL_PATH
    value: /custom-tools/kubectl

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_BACKEND
    value: sops

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
    value: "false"

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
    value: "true"

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
    value: "false"

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_WRAPPER_ENABLED
    value: "true"

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_HELM_PATH
    value: /usr/local/bin/helm

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: HELM_SECRETS_DEBUG
    value: "true"

- op: add
  path: '/spec/template/spec/containers/0/env/-'
  value:
    name: SOPS_AGE_KEY_FILE
    value: /helm-secrets-private-keys/age-key.txt

## Patch volumeMounts
- op: add
  path: '/spec/template/spec/containers/0/volumeMounts/-'
  value:
    mountPath: /custom-tools
    name: custom-tools

- op: add
  path: '/spec/template/spec/containers/0/volumeMounts/-'
  value:
    mountPath: /usr/local/sbin/helm
    name: custom-tools
    subPath: helm

- op: add
  path: '/spec/template/spec/containers/0/volumeMounts/-'
  value:
    mountPath: /helm-secrets-private-keys/
    name: helm-secrets-private-keys-age

## Add download-tools init container

- op: add
  path: '/spec/template/spec/initContainers/-'
  value:
    image: <MY-BUILT-IMAGE>
    imagePullPolicy: IfNotPresent
    name: download-tools
    command: [sh, -ec]
    args:
      - |
        mkdir -p /custom-tools/helm-plugins/helm-secrets
        cp -r /home/user/.local/share/helm/plugins/helm-plugins/helm-secrets /custom-tools/helm-plugins/
        cp /home/user/.local/share/helm/plugins/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm
        cp /usr/local/bin/sops /custom-tools/
        cp /usr/local/bin/kubectl /custom-tools/
        chmod -R +x /custom-tools/*
        cat << EOF > /custom-tools/secret.enc.yaml
        image:
            repository: ENC[AES256_GCM,data:AXvWRbQ=,iv:h/xskM4dREicvnHuTOdEpeUNtaDbbQ9Nl+fSUFSgdCU=,tag:PXOx1AVrrtKjR+TAj4ePEw==,type:str]
            tag: ENC[AES256_GCM,data:eYryx950,iv:VbJM3j7Ts20m2y9wymVkn0oq/3DEoJEoi1QPIYdpBYs=,tag:NDCXo2ymbIqIsvWKvbRWRg==,type:str]
        sops:
            kms: []
            gcp_kms: []
            azure_kv: []
            hc_vault: []
            age:
                - recipient: age1r0ek70gt9kk9ca8gx8f6yd8urtmm77r44v973hjefy6rkuzg4c6qph4n5z
                  enc: |
                    -----BEGIN AGE ENCRYPTED FILE-----
                    YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb3BWL1JBYlRQbG1KUE01
                    bzltcEFERmVXdmhJUldacFpTYWVlRDJCb0VZCmg1R25BV3pJR3Uzb05peFZnVUg5
                    UUhVYUhkM1hsVjJoa0VDdTVxUkhMVk0KLS0tIGdlQmtGS2EyNnpYdTRaeUQrYU1W
                    TXNaaVVUUE9XZS94VWFxenZNUTdEbEkKJTUd6HxwP4JZHMtKjaORKpJiu8+VVHGT
                    /4Hj+FftH/Y3JldanjfYXt8Gcgas3gq1mfvJ3w41MoStAPeGd+wupg==
                    -----END AGE ENCRYPTED FILE-----
            lastmodified: "2023-07-28T13:31:20Z"
            mac: ENC[AES256_GCM,data:pQy8yOIVoThknYh0afoRyRaCMMiIxpicsWvzSJEIdsH62FzW60Xm/MRjgB06XgsUzAqTIA7mQV8UYE195Ybh6Xo8K6iG/Z7DQ0wRiLgRDA0D6VaUtVbpMTxPlFezs/8sFDeQlCdyz14vxD0IX1g4ppE4wmua8xBNz93ORavIhFI=,iv:B/eUrN1kSB+bJFAuBBgKurx9zRqBFKQzF5SCL3JvR/I=,tag:GvU8AJOvv5jizx8DUZcrfg==,type:str]
            pgp: []
            unencrypted_suffix: _unencrypted
            version: 3.7.3

    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

## Patch volumes

- op: add
  path: '/spec/template/spec/volumes/-'
  value:
    emptyDir: {}
    name: custom-tools

- op: add
  path: '/spec/template/spec/volumes/-'
  value:
    name: helm-secrets-private-keys-age
    secret:
      secretName: helm-secrets-private-keys-age

</pre>
</details>

#### Problem description

Argo can't create an Application
![image](https://github.com/jkroepke/helm-secrets/assets/33910251/b3832d68-7f48-447a-bb99-3cbc93749571)

The error text is below. HELM_SECRETS_DEBUG set to "true"

```
+ /custom-tools/sops --decrypt --input-type yaml --output-type yaml secrets.enc.yaml Failed to get the data key required to decrypt the SOPS file. Group 0: FAILED age1r0ek70gt9kk9ca8gx8f6yd8urtmm77r44v973hjefy6rkuzg4c6qph4n5z: FAILED - | error at line 1: malformed secret key: separator '1' at | invalid position: pos=-1, len=6 Recovery failed because no master key was able to decrypt the file. In order for SOPS to recover the file, at least one key has to be successful, but none were. 
+ [ = ] 
```

[full-unformated-error.txt](https://github.com/jkroepke/helm-secrets/files/12196166/full-unformated-error.txt)

But when I try to run this command on the "argo-repo-server" Pod, it passes successfully 
```
argocd@argocd-repo-server-6d748d8d47-2z4dk:/custom-tools$ /custom-tools/sops --decrypt --input-type yaml --output-type yaml secret.enc.ya
ml
image:
    repository: nginx
    tag: latest
argocd@argocd-repo-server-6d748d8d47-2z4dk:/custom-tools$
```

### Expected Behavior

`helm-secrets` plugin don't fail with `Failed to get the data key required to decrypt the SOPS file. Group 0: FAILED` error

### Environment

- Helm Version: v3.11.2
- Helm Secrets Version: 4.4.2
- ArgoCD Version v2.7.9

**Comment by azunna1** [comment]
The reason is due to this issue #384 . I wonder why the tag hasn't been updated yet or a new one created as it affects all users. As a workaround, you should pull the wrapper script directly in your init container:
```yaml
      args:
        - |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v$${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;
          wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64;
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v$${SOPS_VERSION}/sops-v$${SOPS_VERSION}.linux;
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v$${KUBECTL_VERSION}/bin/linux/amd64/kubectl;
          wget -qO- https://github.com/helmfile/vals/releases/download/v$${VALS_VERSION}/vals_$${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;
          wget -qO- https://raw.githubusercontent.com/jkroepke/helm-secrets/main/scripts/wrapper/helm.sh > /custom-tools/helm ;
          chmod +x /custom-tools/* 
```

**Comment by jkroepke** [comment]
@azunna1 I disagree with you.

The error from #384 is related to kustomize, but this error is related to sops.

**Comment by ArtemShevelyukhin** [comment]
@jkroepke so, what is the next step ? Will you create a ticket to sops or you expect anything from me ?

**Comment by jkroepke** [comment]
Hi @ArtemShevelyukhin I looked into this issue today.

The issue here is that you are using the `secrets+age-import://` handler. The handler requires the age key file first

`secrets+age-import://<key-volume-mount>/<key-name>.txt?<relative/path/to/the/encrypted/secrets.yaml>`

If you define `secrets+age-import://secrets.enc.yaml`, then sops tries to interpret the secrets.enc.yaml as AGE keyfile, too.

In this case, `secrets://` handle should be sufficent.
