### ISSUE TITLE
ArgoCD Helm Secrets with SOPS - Unable to resolve relative secrets.yaml paths

### ISSUE THREAD

**Issue by aadje** [jkroepke/helm-secrets#393]
### Current Behavior

I've configured a custom Repo Server which uses SOPS+Age according to the [ArgoCD Integration](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration) help.
When I try to reference a secrets.yaml on any relative or absolute repo path, my Argo Syncs always result in `[helm-secrets] File does not exist: secrets.yml Error: plugin "scripts/run.sh downloader"` errors. 

The only way Argo+helm-secrets is able to find and decrypt the file is when I manually copy my secrets.yaml to my repo-server pod.

### Expected Behavior

helm-secrets should be able to resolve secret files which are committed alongside the Argo Application or by using a relative path starting at the repo root. 

### Steps To Reproduce

```markdown
Reference a secrets.yaml valuesFile using any of these paths
`- secrets+age-import:///helm-secrets-private-keys/keys.txt?secrets.yaml`
`- secrets+age-import:///helm-secrets-private-keys/keys.txt?/apps/my-app/secrets.yaml`
`- secrets://secrets.yaml`

This results in `[helm-secrets] File does not exist: secrets.yml Error: plugin "scripts/run.sh downloader"`

Copy the secrets.yaml to the repo-server pod using
`kubectl cp secrets.yaml "argocd/argo-cd-argocd-repo-server-xxxxxxx-xxxxx:/tmp/secrets.yaml"`
Change the valueFiles url to an absolute OS path
`- secrets+age-import:///helm-secrets-private-keys/keys.txt?/tmp/secrets.yaml` 
Argo finds the file, decrypt the values and Sync de Application
```

### Environment

- Helm Version: `3.11.2`
- Helm Secrets Version: `4.5.0`
- ArgoCD Version: `2.7.8`
- OS: `Local k3s Kubernetes cluster`
- Shell: `bash`
- Current Dockerfile 
```
FROM quay.io/argoproj/argocd:v2.7.8
ARG SOPS_VERSION="3.7.3"
ARG HELM_SECRETS_VERSION="4.5.0"
ARG KUBECTL_VERSION="1.26.3"

ENV HELM_SECRETS_BACKEND="sops" \
    HELM_SECRETS_HELM_PATH=/usr/local/bin/helm \
    HELM_PLUGINS="/home/argocd/.local/share/helm/plugins/" \
    HELM_SECRETS_IGNORE_MISSING_VALUES=true \
    HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL=true \
    HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR=true

USER root
RUN apt-get update && \
    apt-get install -y \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -fsSL https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl

RUN curl -fsSL https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux \
    -o /usr/local/bin/sops && chmod +x /usr/local/bin/sops

RUN ln -sf "$(helm env HELM_PLUGINS)/helm-secrets/scripts/wrapper/helm.sh" /usr/local/sbin/helm

ENV HELM_SECRETS_DEBUG=true

USER 999

RUN helm plugin install --version ${HELM_SECRETS_VERSION} https://github.com/jkroepke/helm-secrets
```

### Anything else?

This issue seems similar to https://github.com/jkroepke/helm-secrets/issues/389

**Comment by jkroepke** [comment]
The error shows me `File does not exist: secrets.yml`

but the examples reference to `secrets.yaml`. Can you confirm, there is no typo somewhere?

**Comment by aadje** [comment]
Sorry, I pasted an older error message, the typo wasn't the issue. 
I'm currently installing local charts. After some more trial and error, I noticed the secrets.yaml files are relative to the chart path and absolute paths do not work, which is fine. 
I'm also able to reference secrets in my `apps` folder and outside my `charts` folder, by going up 2 directories. 
```
kind: Application
spec:
  source:
    path: charts/test-chart
    helm:
      releaseName: test-application
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/keys.txt?../../apps/my-app/secrets.yaml
```
Thanks!

**Comment by jkroepke** [comment]
For security reason, relative paths are disabled

https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments#disable-path-traversal

But you can enabled it with `HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL=true`

**Comment by jkroepke** [comment]
Please also test, if `secrets+age-import:///helm-secrets-private-keys/keys.txt?apps/my-app/secrets.yaml` may works. not sure, if ArgoCD really changes the work dir.

Are you able to test helm secrets on the argocd-repo-server?

**Comment by aadje** [comment]
`secrets+age-import:///helm-secrets-private-keys/keys.txt?apps/my-app/secrets.yaml` results in the Argo Application trying to load a `/charts/test-chart/apps/my-app/secrets.yaml` secrets file, so the Working Directory seems to be relative to the Chart directory.

**Comment by aadje** [comment]
Yes, I have HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL enabled. It's in the Dockerfile in the issue description.
This works with the `secrets+age-import:///helm-secrets-private-keys/keys.txt?../../apps/my-app/secrets.yaml` syntax, which I ended up using successfully.

**Comment by jkroepke** [comment]
Ah, I miss-read you comment and didnt get the notice that you solved it.
