### ISSUE TITLE
Using AWS KMS asymmetric keys

### ISSUE THREAD

**Issue by meenaravichandran1** [jkroepke/helm-secrets#395]
### Problem Statement

This is a question rather than an issue.

When I try to encrypt with an asymmetric KMS key I get the following exception:

`Could not generate data key: [failed to encrypt new data key with master key "arn:aws:kms:ap-south-1:1234567:key/137axxx3-xxxx-4303-9xxx-c0xxxxxxxd": Failed to call KMS encryption service: InvalidKeyUsageException: Algorithm SYMMETRIC_DEFAULT is incompatible with key spec RSA_3072.]`

Is it a limitation of SOPS that only symmetric keys are supported or something could be changed in this project to support asymmetric keys as well?

### Environment

- Helm Version:
- Helm Secrets Version:
- OS:
- Shell:

**Comment by jkroepke** [comment]
It seems an limitation with sops

https://github.com/getsops/sops/issues/684


----


helm-secrets also supports vals as backend.
https://github.com/helmfile/vals#aws-kms

but it sounds more complicated. With vals, you can only encrypt/decrypt single properties, but not a whole file.
