### ISSUE TITLE
file not found issues after upgrading secrets plugin

### ISSUE THREAD

**Issue by ckopparthi** [jkroepke/helm-secrets#398]
### Current Behavior

helm template . -f 'secret://secrets.test.yaml'
Error: open secret://secrets.test.yaml: no such file or directory

### Steps To Reproduce

```markdown
1. upgrade the helm secrets plugin from 3.4.1 to 4.5.0
2. run helm template/upgrade using helm `helm template . -f 'secret://secrets.test.yaml'`
```

### Environment

- Helm Version: version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
- Helm Secrets Version: 4.5.0
- ArgoCD Version
- OS: mac
- Shell: zsh

**Comment by jkroepke** [comment]
you can please rerun your command with `helm --debug template` and share the output here?

**Comment by ckopparthi** [comment]
below is the debug output 
```
 helm template . -f 'secret://secrets.test.yaml' --debug
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /Users/ckopparthi/temp/test-secret

Error: open secret://secrets.test.yaml: no such file or directory
helm.go:84: [debug] open secret://secrets.test.yaml: no such file or directory
```
but the file is already present in the path 
```
 test-secret pwd
/Users/ckopparthi/temp/test-secret

ls secrets.test.yaml
secrets.test.yaml
```

**Comment by jkroepke** [comment]
Could you please try `secrets://` instead  `secret://`.

**Comment by ckopparthi** [comment]
Thanks  for quick response @jkroepke after using the `secrets://` it worked, but `secret://` used to work in earlier versions

**Comment by jkroepke** [comment]
It was removed in version [4.0.0](https://github.com/jkroepke/helm-secrets/blob/main/CHANGELOG.md#400---2022-09-11)
