### ISSUE TITLE
ArgoCD 2.8.3 with Helm Secrts " gpg: no valid OpenPGP data found"

### ISSUE THREAD

**Issue by wofr** [jkroepke/helm-secrets#403]
### Current Behavior

I did use Helm Secerts with ArgoCD 2.7.6, evything worked fine.  

Today I did an update of ArgoCD 2.8.3, there fore I also updated the argocd-server and used the DockerFile (below) like recommaned here (
`https://github.com/jkroepke/helm-secrets/blob/821ca3f6e41ddc3cb81ac72aca0e7aa09bf9bf52/docs/ArgoCD%20Integration.md`) 

The Docker Image looks now like this
```
FROM quay.io/argoproj/argocd:v2.8.3
ARG SOPS_VERSION="3.7.1"
ARG VALS_VERSION="0.24.0"
ARG HELM_SECRETS_VERSION="4.5.0"
ARG KUBECTL_VERSION="1.26.1"
# vals or sops
ENV HELM_SECRETS_BACKEND="vals" \
    HELM_SECRETS_HELM_PATH=/usr/local/bin/helm \
    HELM_PLUGINS="/home/argocd/.local/share/helm/plugins/" \
    HELM_SECRETS_VALUES_ALLOW_SYMLINKS=true \
    HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH=true \
    HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL=true \
    HELM_SECRETS_WRAPPER_ENABLED=true

# Optionally, set default gpg key for sops files
# ENV HELM_SECRETS_LOAD_GPG_KEYS=/path/to/gpg.key

USER root
RUN apt-get update && \
    apt-get install -y \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -fsSL https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl

# sops backend installation (optional)
RUN curl -fsSL https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux \
    -o /usr/local/bin/sops && chmod +x /usr/local/bin/sops

# vals backend installation (optional)
RUN curl -fsSL https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz \
    | tar xzf - -C /usr/local/bin/ vals \
    && chmod +x /usr/local/bin/vals

RUN ln -sf "$(helm env HELM_PLUGINS)/helm-secrets/scripts/wrapper/helm.sh" /usr/local/sbin/helm


RUN helm plugin install --version ${HELM_SECRETS_VERSION} https://github.com/jkroepke/helm-secrets

USER 999
```

Unfortunatly now the encyrption does not work anymore. I do get the following errors when I try to deploy somthing using ArgoCD

```
...pi-versions warden.gke.io/v1 --api-versions warden.gke.io/v1/Audit --include-crds` failed exit status 2: gpg: no valid OpenPGP data found.\nError: plugin \"secrets\" exited with error"
```

The key file is still the same I used with ArgoCD 2.7.6 (I used helm secrets 4.4.2) there. 

### Expected Behavior

Using ArgoCD with Helm secrets should not throw an exectptoin

### Steps To Reproduce

```markdown
argocd: v2.8.3+77556d9
  BuildDate: 2023-09-07T17:39:16Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.8.3+77556d9
  BuildDate: 2023-09-07T16:05:43Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

Helm Secrts version 4.5.0
```

**Comment by jkroepke** [comment]
If you jump into the pod, are you able decrypt the secrets? Vis helm secrets decrypt?

**Comment by jkroepke** [comment]
Seems like you are using sops, but from Dockerfile point of view, vals is configured `HELM_SECRETS_BACKEND="vals" `. Can you validate this?

**Comment by wofr** [comment]
Yes I'm using SOPS

**Comment by wofr** [comment]
unfortunatly I still have the same issue.

**Comment by wofr** [comment]
Out of the blue the call above works now!! Unfortunatly I do now get the error we seen above for all my existing applications (appsets).  Evenso if I remove the HELM-Secrets from the argocde-repo-server.  

I'm very confused now.  Maybe its a cache problem of Argocd

**Comment by jkroepke** [comment]
> Maybe its a cache problem of Argocd

Yes. It's caching by design... By default ArgoCD caches manifest for 24 hours based on commit has. You can restart the redis to clear all caches. Alternativly. The UI has on option for Hard Refresh on each application

**Comment by wofr** [comment]
It really seemed that the cache kept me hostile!  A early missconfiguration seems to caused the error descirbed above, an than changes seemed to be ignored due to the cache.

thanks for your support.

**Comment by wofr** [comment]
Beside the cache issue I had, I do have to remove setting the `HELM_SECRETS_LOAD_GPG_KEYS` in the `argocd-repo-server` deployment, otherwise I run into the ``` failed exit status 2: gpg: no valid OpenPGP data found.%0AError: plugin \"secrets\" exited with error```  error! 

The mounts of the voumens I've kept.

```
repoServer:
  env:
    - name: HELM_SECRETS_LOAD_GPG_KEYS
      # Multiple keys can be separated by space
      value: /helm-secrets-private-keys/key.asc
```
