### ISSUE TITLE
Multiline strings passed with --set being cut

### ISSUE THREAD

**Issue by metrictwo** [jkroepke/helm-secrets#404]
### Current Behavior

When passing a multi-line value via `--set`, only the first line of the value is available to the chart when using the plugin.

### Expected Behavior

The full multi-line value is available to the chart, as is the case with the regular `helm` command.

### Steps To Reproduce
Make an example chart with the following template:
```markdown
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline
data:
  multiline: {{ .Values.multiline | quote }}
```
When templating this chart with a multiline value, only the first line is available:
```
$ helm secrets template helm-charts/multiline \
  --set multiline="key1:
  key2: value"
---
# Source: multiline/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline
data:
  multiline: "key1:"
```
When using the bare helm command, the full string is available:
```
$ helm template helm-charts/multiline --set multiline="key1:
  key2: value"
---
# Source: multiline/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline
data:
  multiline: "key1:\n  key2: value"
```

### Environment

- Helm Version: 3.11.2
- Helm Secrets Version: 4.4.2
- ArgoCD Version: 2.7.14
- OS: Linux
- Shell: /bin/sh

### Anything else?
For context, we tried to enable the helm wrapper in our `argocd-repo-server` image to support multi-source applications. The secret functionality worked perfectly, but we noticed this issue with a dynamic multiline parameter and had to roll back.

**Comment by jkroepke** [comment]
Thanks for the report. I was able to reproduce it and should now resolved on main

**Comment by metrictwo** [comment]
Fantastic, thank you very much @jkroepke. Do you know when the next release is going to be cut?
