### ISSUE TITLE
helm secrets decrypt not creating .dec file but outputs in console

### ISSUE THREAD

**Issue by strassea** [jkroepke/helm-secrets#416]
### Current Behavior

when decrypting I only get the (decrypted) content returned in the console, but the .dec file does not get created. The command used was
```
helm secrets decrypt secrets.yaml 
```
inline decryption works fine though. Is this exprected behaviour?

### Environment

- Helm Version: 3.12.2
- Helm Secrets Version: 4.4.2
- OS: WSL Debian bullseye
- Shell: bash
- encrypted with sops

**Comment by jkroepke** [comment]
>  Is this exprected behaviour?
Yes. Use `helm secrets decrypt secrets.yaml  > secrets.yaml.dec` to write the decrypted content to an file

**Comment by strassea** [comment]
got it, thank you very much!
