### ISSUE TITLE
[Question] Passing VAULT_NAMESPACE env var in helm-secrets plugin with ArgoCD 

### ISSUE THREAD

**Issue by jaythamke** [jkroepke/helm-secrets#419]
Hello Jan,
I am currently testing some scenarios in our CD workflow with ArgoCD. 
I am already using _helm-secrets_ plugin along with _sops_ for managing the secrets since two years. Thanks for your efforts.
In my current scenario, the secrets encryption and decryption are done by the keys stored in Hashicorp Vault (Enterprise version) Transit engines and the keys are separated by using Vault namespaces (e.g. /dev/, /staging/ etc. ) (defined by `VAULT_NAMESPACE` env variable).

I would like to know how to pass `VAULT_NAMESPACE` and `VAULT_TOKEN` env var to `argocd-repo-server` from ArgoCD Application.

**Comment by jkroepke** [comment]
ArgoCD App are not able to inject environment variables.

Do you have separat VAULT_TOKEN for each Application?

**Comment by jaythamke** [comment]
> ArgoCD App are not able to inject environment variables.
> 
> Do you have separat VAULT_TOKEN for each Application?

Yes, I have to create new VAULT_TOKEN for each VAULT_NAMESPACE

**Comment by jaythamke** [comment]
> ArgoCD App are not able to inject environment variables.

Thanks for quick reply!
In that case, I think I have to come up with argocd-plugin like solution (provided in https://argocd-vault-plugin.readthedocs.io/en/stable/usage/) and then rendering K8s manifests by using `helm secrets template -f my-sops-enc-secret.yaml -f some-other-values.yaml`

**Comment by jaythamke** [comment]
Closing as query is resolved
