### ISSUE TITLE
support subchart decrypt

### ISSUE THREAD

**Issue by owanio1992** [jkroepke/helm-secrets#428]
### Problem Statement

I want use a shared chart to save secret 
and other chart use dependencies to include this secret charts 

but current I can't decrypt sub chart (use -f secrets://charts/subchart_value.yaml   the value become parent charts' value )

### Proposed Solution

can just auto detect yaml is encrypt ? and auto decrypt ? 
that's will be easier use helm secret 

### Environment

- Helm Version: v3.13.3
- Helm Secrets Version: 4.5.1
- OS: ubuntu
- Shell: bash

**Comment by jkroepke** [comment]
Are you using sops or age encryption?

> but current I can't decrypt sub chart (use -f secrets://charts/subchart_value.yaml the value become parent charts' value )

You can mitigate this by 

* Override subchart values from parent chart: (https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart)
* Using global scope: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values

**Comment by owanio1992** [comment]
I'm use sops encryption
thanks for give me advise
I will try use global value to accomplish

**Comment by jkroepke** [comment]
I guess there is no other alternative then
