### ISSUE TITLE
helm template for secrets

### ISSUE THREAD

**Issue by Nikhilsrh07** [jkroepke/helm-secrets#447]
### Problem Statement

need generate helm template for helm secrets. kind of dry run 

### Environment

Helm Version: 3.7.1
Helm Secrets Version: 3.12.0
*OS: Alpine
*Shell: busybox

**Comment by jkroepke** [comment]
Just run 

helm template -f secrets://secrets.yaml

**Comment by Nikhilsrh07** [comment]
actually, I'm looking for this solution. 

helm templates secrets -f secrets app  . which is similar to (helm secrets -f secrets app .)

**Comment by jkroepke** [comment]
I dont get it

**Comment by Nikhilsrh07** [comment]
usually after we install helm secrets plugin.
this command  helm secrets upgrade -f secrets app .  works if we upgrade helm-chart with secrets 
 and also helm template -f secrets app . also works.
 here I haven't upgraded helm chart with secrets but encrypted them and want to test them with template.
 I'm here trying to pass encrypted secrets through values file.
 helm secrets template -f secrets .yaml app .
