### ISSUE TITLE
Helm Secrets does not support spaces in windows user name

### ISSUE THREAD

**Issue by raulriverarojas** [jkroepke/helm-secrets#466]
### Current Behavior

Any helm secrets command fails on a system where the window user has a space in its name:

C:\Users\J K Computers Inc>helm secrets --version
'C:\Users\J' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "secrets" exited with error

Specifying the helm path does not help either:
C:\Users\J K Computers Inc>"C:\ProgramData\chocolatey\bin\helm.exe" secrets --version
'C:\Users\J' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "secrets" exited with error

### Expected Behavior

Compared to commands where the user does not:
C:\Users\Spaceman>helm secrets --version
4.6.1-dev

### Steps To Reproduce

```markdown
1. Use a windows machine with spaces in its name
2. Install helm and secrets 
3. Run helm secrets --version
```

### Environment

- Helm Version:
version.BuildInfo{Version:"v3.14.1", GitCommit:"e8858f8696b144ee7c533bd9d49a353ee6c4b98d", GitTreeState:"clean", GoVersion:"go1.21.7"}
- Helm Secrets Version: 3.9.0
- ArgoCD Version
- OS: Window 10 Pro 22H2
- Shell: cmd

**Comment by jkroepke** [comment]
Year ago, there was an bug in helm.

https://github.com/helm/helm/pull/10913

It should fixes in recent helm versions.

Could please add the --debug flag and post the output?

helm --debug secrets version

**Comment by raulriverarojas** [comment]
> Year ago, there was an bug in helm.
> 
> [helm/helm#10913](https://github.com/helm/helm/pull/10913)
> 
> It should fixes in recent helm versions.
> 
> Could please add the --debug flag and post the output?
> 
> helm --debug secrets version

C:\Users\J K Computers Inc>helm --debug secrets version
'C:\Users\J' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "secrets" exited with error
helm.go:84: [debug] plugin "secrets" exited with error

**Comment by jkroepke** [comment]
Please run

```
helm plugin uninstall secrets
helm plugin install https://github.com/jkroepke/helm-secrets --version space
```

And let me know, if the changes from #467 helps

**Comment by raulriverarojas** [comment]
> Please run
> 
> ```
> helm plugin uninstall secrets
> helm plugin install https://github.com/jkroepke/helm-secrets --version space
> ```
> 
> And let me know, if the changes from #467 helps

Thanks for the quick response! Got this:

C:\Users\J K Computers Inc>helm version
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>helm secrets version --debug

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg2.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>if not "" == "" GOTO :ENVSH

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>"C:\Program Files\Git\bin\bash.exe" -c exit   1>nul 2>&1

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 GOTO :GITBASH

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>"C:\Program Files\Git\bin\bash.exe" "'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh'" version
/usr/bin/bash: 'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh': No such file or directory

C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts>exit /b 127
Error: plugin "secrets" exited with error
helm.go:84: [debug] plugin "secrets" exited with error

Helm secrets does have a run.sh file there:

 Directory of C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts

2024-07-31  05:03 PM    <DIR>          .
2024-07-31  05:03 PM    <DIR>          ..
2024-07-31  05:03 PM    <DIR>          commands
2024-07-31  05:03 PM    <DIR>          lib
2024-07-31  05:03 PM             7,142 run.sh
2024-07-31  05:03 PM    <DIR>          wrapper

**Comment by jkroepke** [comment]
> Helm secrets does have a run.sh file there:

There is one, in your output:

> 2024-07-31 05:03 PM 7,142 run.sh

**Comment by jkroepke** [comment]
> Or is this a plugin issue?

It's still an plugin issue. I test it yesterday only with WSL. The error is technically correct: `'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh'` can never exists, because in that situation, the bash things the quotas are actual a real part of that script path.

**Comment by jkroepke** [comment]
idk, if I'm running helm-secrets with that version on my system, I can't reproduce the issue:

```

PS C:\Users\Jan\a b> helm secrets version --debug

C:\Users\Jan\a b>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\Jan\a b>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg2.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\Jan\a b>if not "" == "" GOTO :ENVSH

C:\Users\Jan\a b>"C:\Program Files\Git\bin\bash.exe" -c exit   1>nul 2>&1

C:\Users\Jan\a b>IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 GOTO :GITBASH

C:\Users\Jan\a b>"C:\Program Files\Git\bin\bash.exe" 'C:\Users\Jan\a b\plugins\helm-secrets\scripts\run.sh' version
+ SCRIPT_DIR='C:\Users\Jan\a b\plugins\helm-secrets/scripts'
+ . 'C:\Users\Jan\a b\plugins\helm-secrets/scripts/lib/common.sh'
```
maybe uninstall the plugin, clear the cache (%USERPROFILE%\AppData\Local\Temp\helm) and reinstall could help.

**Comment by raulriverarojas** [comment]
Cleared the cache in the TEMP folder and reinstalled. Still getting this output.

C:\Users\J K Computers Inc>helm plugin install https://github.com/jkroepke/helm-secrets --version space
Installed plugin: secrets

C:\Users\J K Computers Inc>helm version
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}

C:\Users\J K Computers Inc>helm secrets
/usr/bin/bash: 'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh': No such file or directory
Error: plugin "secrets" exited with error

C:\Users\J K Computers Inc>helm secrets version --debug

C:\Users\J K Computers Inc>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\J K Computers Inc>IF NOT DEFINED SOPS_GPG_EXEC (
where /q gpg2.exe
 IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 (FOR /F "tokens=* USEBACKQ" %F IN (`where gpg.exe`) DO (SET SOPS_GPG_EXEC=%F ) )
)

C:\Users\J K Computers Inc>if not "" == "" GOTO :ENVSH

C:\Users\J K Computers Inc>"C:\Program Files\Git\bin\bash.exe" -c exit   1>nul 2>&1

C:\Users\J K Computers Inc>IF ERRORLEVEL 0 IF NOT ERRORLEVEL 1 GOTO :GITBASH

C:\Users\J K Computers Inc>"C:\Program Files\Git\bin\bash.exe" "'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh'" version
/usr/bin/bash: 'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh': No such file or directory

C:\Users\J K Computers Inc>exit /b 127
Error: plugin "secrets" exited with error
helm.go:84: [debug] plugin "secrets" exited with error



The debug output is showing that the run.sh path has both " and ' quotations around it. Removing either and running the command direcly gives the output:

C:\Users\J K Computers Inc>"C:\Program Files\Git\bin\bash.exe" 'C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh' version
C:\Users\J K Computers Inc\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh: line 10: HELM_PLUGIN_DIR: unbound variable

**Comment by jkroepke** [comment]
Cloud you please do that again to validate the latest changes?

```
helm plugin uninstall secrets
helm plugin install https://github.com/jkroepke/helm-secrets --version space
```

**Comment by raulriverarojas** [comment]
C:\Users\J K Computers Inc>helm plugin install https://github.com/jkroepke/helm-secrets --version space
Installed plugin: secrets

C:\Users\J K Computers Inc>helm secrets --version
4.6.1-dev
Perfect! Thank you!
