### ISSUE TITLE
Allow git remote repository file 

### ISSUE THREAD

**Issue by jBouyoud** [jkroepke/helm-secrets#50]
Hello, 

This is about a new feature : 
> Allow to gain secrets file from remote location (in this case from git repository)

This issue should be about how to implement it. 
I'll see the following options: 

## Not here
This is not the purpose of this plugin. Let's create a specific one, or your specific driver....

**Pros**
* No new code here

**Cons**
* helm command growth more and more ;-)
* this is not very huge logic 

## Add a new kind of driver to be able to retrieve file from a location
Introduce a new kind of driver. Interface could be something like `is_supported $1` ; `get_content $1`

**Pros**
* Extensible
* Retrieve logic is well sperated, is it growth is could be easilly moved in another plugin

**Cons**
* Introduce a second kind of driver (global complexity)

## As a new driver 
Build a new `sops_git` driver 

**Pros**
* Isolated

 **Cons**
* Need to change the actual driver interface, need to add a `driver_is_supported_file` , and replace all `[ -f ... ]` 
* Specific (get a remote file and then decrypt with sops, or with vault)

I'll be glad to create a PR on that subject, please let me know.

**Comment by jkroepke** [comment]
Looking at the helm documentation, helm supports multiple method to get an value file

* Filesystem
* HTTP
* 3rd Party Plugin

helm-secret should also support that to be consistent with helm.

I don't know howto get files through helm via 3rd party plugin outside helm, but http could be done nativly.

Getting remote files other the 3 method provided by helm are out of scope.

Most of the git repositories are accessable via http rest api, if you are using some UI for git projects.

**Comment by jkroepke** [comment]
@jBouyoud combined with https://awesomeopensource.com/project/aslafy-z/helm-git this could your solution then.

**Comment by jBouyoud** [comment]
I don't catch that in the doc. 
I'll check that.
Thanks

**Comment by jkroepke** [comment]
> I don't catch that in the doc.

Yes, It's not documented.

**Comment by jkroepke** [comment]
See it here in action now:

https://github.com/jkroepke/helm-secrets/blob/0c5b62d4011c7465355c29e905a6b9d5823ee545/tests/unit/template.bats#L263

**Comment by jBouyoud** [comment]
Very nice 💪
