### ISSUE TITLE
Incorrect vault_regexp

### ISSUE THREAD

**Issue by CrazyTushkan** [jkroepke/helm-secrets#78]
Hi, trying to use vault driver and getting grep error.
I'm not sure why, but `[A-z]*` leads to `grep: Invalid range end` error.
Replacing it with `[a-zA-Z]` seems to resolve this.

**Comment by zied-jt** [comment]
Hi, I'm also affected by the `grep: Invalid range end` with the vault driver. I think that it's related to how `locale` are set in the user env for **Linux users**.
 
From `grep` manual:
> LC_ALL, LC_COLLATE, LANG
              These variables specify the locale for the LC_COLLATE category, which determines the collating sequence used to interpret range expressions like [a-z].

With setting `LC_COLLATE=C` (or  `LC_COLLATE=POSIX`) by exporting the var to the current shell (it could change other tools behaviors like sort, so careful if it will be set as default value: https://unix.stackexchange.com/questions/75341/specify-the-sort-order-with-lc-collate-so-lowercase-is-before-uppercase)

@jkroepke what about either having a hint about this in the README or forcing `LC_COLLATE` in the `helm-secret` grep at line https://github.com/jkroepke/helm-secrets/blob/main/scripts/drivers/_custom.sh#L18

**Comment by jkroepke** [comment]
Crazy errors. 

@zied-jt Thanks for figure it out.

What about just put the env in front of the regex command, like:

```
LC_ALL=C.UTF-8 grep -q -e "${_DRIVER_REGEX}" "${input}"
```

That should be resolve the error in general without leaving a hint.

**Comment by zied-jt** [comment]
@jkroepke Thanks for the quick replay. I'm ok with your fix.

I want also to thank @rasta-rocket for helping me figure out this weird error.

**Comment by jkroepke** [comment]
Could someone verifies that this is working?

https://github.com/jkroepke/helm-secrets/pull/79

**Comment by CrazyTushkan** [comment]
@jkroepke It certainly fixes my case, thanks!)
