### ISSUE TITLE
Question: How to use with terraform helm provider?

### ISSUE THREAD

**Issue by dgradl** [jkroepke/helm-secrets#85]
In the README.md it describes using downloader to apply and says "Useful if you plan to use the helm terraform provider."   Do you have an example of how it would be used together?

**Comment by jkroepke** [comment]
Hi @dgradl 

it looks like I recently miss understood the documentation on docs.terraform.io. Last time I read it, I thought, terraform is passing the values to the helm command. But the helm provider want to read the yaml files directly. Currently it's not possible since the helm provider does not have the ability to use the "downloader plugins" at values level.

**Comment by jkroepke** [comment]
I raised a issues a the helm terraform provider about this topic. If its resolved, this plugin could be used with the terraform provider

**Comment by dgradl** [comment]
Thanks yeah, I also kind of thought the values field should handle files since there was the set alternative.  I'm watching the ticket you opened and gave it a vote.

**Comment by jkroepke** [comment]
You can find an example here https://github.com/jkroepke/helm-secrets/blob/main/contrib/terraform/chart.tf

**Comment by dgradl** [comment]
Thanks!

**Comment by rsmets** [comment]
> You can find an example here https://github.com/jkroepke/helm-secrets/tree/main/contrib/terraform

I believe this is the new url for the example https://github.com/jkroepke/helm-secrets/blob/main/examples/terraform/helm.tf

Curious if anyone was ever able to get that to work though? No luck on this end.

**Comment by jkroepke** [comment]
Hum, I test this locally and I even have tests for the example provided above.

https://github.com/hashicorp/terraform-provider-helm/issues/699

**Comment by jkroepke** [comment]
> But Helm complains about no such commands as terraform which makes sense... 

I got it. The terraform command is not released yet. It's currently in main only. Whoops

**Comment by rsmets** [comment]
Ahh hey that makes sense! Glad I wasn't crazy. Neat addition of `terraform` json output for Helm Secrets... even more utility over vanilla Helm binary. Thanks again.

**Comment by jkroepke** [comment]
It's released now in 3.12.0, feel free to test.

**Comment by rsmets** [comment]
Worked like a charm :)
