### ISSUE TITLE
Cleanup temporary files

### ISSUE THREAD

**Issue by dargor** [jkroepke/helm-secrets#88]
Using `secrets 3.5.1-dev` and `sops 3.6.1 (latest)` with `vault` driver, everything works fine but the plugin leaves every yaml unencrypted in `/tmp`.

**Comment by jkroepke** [comment]
Whats your OS?

**Comment by jkroepke** [comment]
@dargor You could do verify if #93 resolves your issues?

It looks like, the handing of temp files was broke in general.

**Comment by dargor** [comment]
I am using Linux (Gentoo).

Just ran tests with #93, all tests passed without any tmpfiles left :)

**Comment by jkroepke** [comment]
Awesome!
