### ISSUE TITLE
mktemp Error Message with v3.6.0

### ISSUE THREAD

**Issue by mattmelgard** [jkroepke/helm-secrets#95]
Hello,

I seem to be getting back an odd error when upgrading a release using the latest version of the plugin (3.6.0).

Example:
```shell
helm secrets upgrade --install sops-demo-app helm -f helm/env/local/secrets.sops.yaml -f helm/env/local/values.yaml --dry-run --debug
mktemp: too few X's in template ‘helm-secrets’
Error: plugin "secrets" exited with error
helm.go:81: [debug] plugin "secrets" exited with error
```

The very same deployment seems to work just fine with the previous version `3.5.0`. 

Here's the versions I'm using:

- **OS:** macOS Big Sur Version 11.2.3
- **Helm:** `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`
- **Kubectl/Cluster:** `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
- **SOPS:** `sops 3.6.1`

Let me know if there's any other info I can provide to help debug.

**Comment by mattmelgard** [comment]
**UPDATE:** I'm also noticing that the decrypted file contents are left on disk rather than being automatically deleted after deployment, even when successfully deploying with `3.5.0`. I'm moving from the original Zendesk managed project so I'm not sure if this was a regression from a previous version or not, but as far back as `3.4.0` I seem to be experiencing the same issue using this fork.

**Comment by jkroepke** [comment]
Hi,

3.6.0 introduce a lot of fixes around temp files. Before 3.6.0, this plugin leaks a lot of temporary files when using the vault driver.

While on macOS Big Sur Version 11.2.3, too. I could not verify this behavior.  

Could you run `mktemp -h`? A quick test shows me that I could reproduce this error on a GNU version of mktemp, which isn't default on Mac OS.

**Comment by mattmelgard** [comment]
@jkroepke gotcha, that makes sense since I do have the GNU coreutils installed. Here's the help output:
```
mktemp --help
Usage: mktemp [OPTION]... [TEMPLATE]
Create a temporary file or directory, safely, and print its name.
TEMPLATE must contain at least 3 consecutive 'X's in last component.
If TEMPLATE is not specified, use tmp.XXXXXXXXXX, and --tmpdir is implied.
Files are created u+rw, and directories u+rwx, minus umask restrictions.

  -d, --directory     create a directory, not a file
  -u, --dry-run       do not create anything; merely print a name (unsafe)
  -q, --quiet         suppress diagnostics about file/dir-creation failure
      --suffix=SUFF   append SUFF to TEMPLATE; SUFF must not contain a slash.
                        This option is implied if TEMPLATE does not end in X
  -p DIR, --tmpdir[=DIR]  interpret TEMPLATE relative to DIR; if DIR is not
                        specified, use $TMPDIR if set, else /tmp.  With
                        this option, TEMPLATE must not be an absolute name;
                        unlike with -t, TEMPLATE may contain slashes, but
                        mktemp creates only the final component
  -t                  interpret TEMPLATE as a single file name component,
                        relative to a directory: $TMPDIR, if set; else the
                        directory specified via -p; else /tmp [deprecated]
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/mktemp>
or available locally via: info '(coreutils) mktemp invocation'
```

**Comment by jkroepke** [comment]
@mattmelgard could you take a look at #96 ?

I simplify the mktemp logic using options only that works on gnu and bsd, too.

**Comment by mattmelgard** [comment]
> #96

Sure, will do

**Comment by mattmelgard** [comment]
> @mattmelgard could you take a look at #96 ?
> 
> I simplify the mktemp logic using options only that works on gnu and bsd, too.
Will do
